import { AgentId } from '@lemon/agents';

export type CommandType = 'REDIRECT' | 'AUXILIARY';
export type CommandCategory = 'ALL' | 'REDIRECT' | 'AUXILIARY' | 'TECH' | 'SURVEY' | 'CONTENT';

export interface ChatCommandMeta {
  id: string;
  command: string;
  label: string;
  emoji: string;
  type: CommandType;
  category: CommandCategory;
  description: string;
  targetThreadKeyword?: string;
  targetAgent?: AgentId;
  defaultPrompt: string;
  isPopular?: boolean;
  tags?: string[];
}

export interface PeriodOption {
  key: 'today' | 'week' | 'month';
  label: string;       // "За день", "За неделю", "За месяц"
  sublabel: string;    // "Срез на сегодня", "Панорама за неделю", "Панорама за месяц"
  command: string;     // "/politics today", "/politics week", "/politics month"
  emoji: string;       // "🏛️", "📅", "🗓️"
  description: string;
  defaultPrompt: string;
}

export interface GroupedCommandMeta {
  id: string;
  baseCommand: string;
  label: string;
  emoji: string;
  type: CommandType;
  category: CommandCategory;
  description: string;
  targetThreadKeyword?: string;
  targetAgent?: AgentId;
  periods: PeriodOption[];
}

export const GROUPED_COMMANDS_REGISTRY: Record<'politics' | 'it' | 'breaking' | 'post', GroupedCommandMeta> = {
  post: {
    id: 'group-post',
    baseCommand: '/post',
    label: 'Telegram Post',
    emoji: '✈️',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Форматирование аналитической сводки в стилизованный Telegram Post с буллетами, резюме и тегами',
    periods: [
      {
        key: 'today',
        label: 'За день',
        sublabel: 'TG Пост за сегодня',
        command: '/post today',
        emoji: '✈️',
        description: 'Стилизованный Telegram-пост со сводкой куратора за сегодня с действиями',
        defaultPrompt: '/post today',
      },
      {
        key: 'week',
        label: 'За неделю',
        sublabel: 'TG Дайджест за неделю',
        command: '/post week',
        emoji: '📅',
        description: 'Стилизованный Telegram-дайджест с ключевыми итогами недели',
        defaultPrompt: '/post week',
      },
    ],
  },
  politics: {
    id: 'group-politics',
    baseCommand: '/politics',
    label: 'Политическая коллегия',
    emoji: '🏛️',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Оперативный модульный и стратегический срез по ключевым контурам (РФ, США, Ближний Восток, Свежие новости)',
    targetThreadKeyword: 'Политическая коллегия',
    targetAgent: 'political-group',
    periods: [
      {
        key: 'today',
        label: 'За день',
        sublabel: 'Срез на сегодня',
        command: '/politics today',
        emoji: '🏛️',
        description: 'Оперативный модульный срез по ключевым контурам за день без фото и лишнего шума',
        defaultPrompt: '/politics today',
      },
      {
        key: 'week',
        label: 'За неделю',
        sublabel: 'Панорама за неделю',
        command: '/politics week',
        emoji: '📅',
        description: 'Краткое недельное резюме по контурам за 7 дней с кнопками перехода в треды кураторов',
        defaultPrompt: '/politics week',
      },
      {
        key: 'month',
        label: 'За месяц',
        sublabel: 'Панорама за месяц',
        command: '/politics month',
        emoji: '🗓️',
        description: 'Стратегический срез за 30 дней: законы РФ, санкции, рынки, Ближний Восток и мировая повестка',
        defaultPrompt: '/politics month',
      },
    ],
  },
  it: {
    id: 'group-it',
    baseCommand: '/it',
    label: 'IT & AI Группа',
    emoji: '⚡',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Технологическая группа: Акация IT (Hi-Tech, девайсы, анонсы), Саймон (Хабр) и Presijo AI & IT (инструменты, библиотеки, Telegram)',
    targetThreadKeyword: 'IT & AI',
    targetAgent: 'tech-group',
    periods: [
      {
        key: 'today',
        label: 'За день',
        sublabel: 'Срез на сегодня',
        command: '/it today',
        emoji: '⚡',
        description: 'Оперативный срез IT & AI за день: девайсы, разбор публикаций с Habr и свежие AI-инструменты',
        defaultPrompt: '/it today',
      },
      {
        key: 'week',
        label: 'За неделю',
        sublabel: 'Панорама за неделю',
        command: '/it week',
        emoji: '📅',
        description: 'Недельный дайджест IT & AI: Hi-Tech анонсы, топ статей Хабра и релизы библиотек',
        defaultPrompt: '/it week',
      },
      {
        key: 'month',
        label: 'За месяц',
        sublabel: 'Панорама за месяц',
        command: '/it month',
        emoji: '🗓️',
        description: 'Стратегический срез за 30 дней: тренды Hi-Tech, инженерные практики и экосистема AI-инструментов',
        defaultPrompt: '/it month',
      },
    ],
  },
  breaking: {
    id: 'group-breaking',
    baseCommand: '/breaking',
    label: 'Breaking News',
    emoji: '🔥',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Экстренные мировые молнии, виральные тренды и срочные новости глобальной повестки',
    targetThreadKeyword: 'Breaking',
    targetAgent: 'alex-vector',
    periods: [
      {
        key: 'today',
        label: 'За день',
        sublabel: 'Пульс за сегодня',
        command: '/breaking today',
        emoji: '🔥',
        description: 'Экстренные мировые молнии, виральные тренды и срочные новости за сегодня',
        defaultPrompt: '/breaking today',
      },
      {
        key: 'week',
        label: 'За неделю',
        sublabel: 'Панорама за неделю',
        command: '/breaking week',
        emoji: '📅',
        description: 'Недельная хроника самых горячих событий, мировых происшествий и трендов',
        defaultPrompt: '/breaking week',
      },
      {
        key: 'month',
        label: 'За месяц',
        sublabel: 'Панорама за месяц',
        command: '/breaking month',
        emoji: '🗓️',
        description: 'Ключевые мировые события и breaking-хроника за 30 дней',
        defaultPrompt: '/breaking month',
      },
    ],
  },
};

export const CHAT_COMMANDS_REGISTRY: ChatCommandMeta[] = [
  // =========================================================================
  // 1. КОМАНДЫ НАВИГАЦИИ И РЕДИРЕКТА В ТРЕДЫ (REDIRECT)
  // =========================================================================
  {
    id: 'cmd-politics-base',
    command: '/politics',
    label: 'Политическая коллегия (Все контуры)',
    emoji: '🏛️',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в тред Политической коллегии: Иван Белый (РФ), Kirk Kitten (США), Тарик Саид (Ближний Восток) и Алекс Вектор (Свежие новости)',
    targetThreadKeyword: 'Политическая коллегия',
    targetAgent: 'political-group',
    defaultPrompt: '/politics today',
    isPopular: true,
    tags: ['политика', 'коллегия', 'рф', 'санкции', 'ближний восток', 'повестка', 'срез'],
  },
  {
    id: 'cmd-politics-today',
    command: '/politics today',
    label: 'Политика: Срез на сегодня',
    emoji: '🏛️',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Оперативный модульный срез по ключевым контурам за день без фото и лишнего шума',
    targetThreadKeyword: 'Политическая коллегия',
    targetAgent: 'political-group',
    defaultPrompt: '/politics today',
    isPopular: false,
    tags: ['политика', 'день', 'сегодня', 'сводка', 'рф', 'санкции'],
  },
  {
    id: 'cmd-politics-week',
    command: '/politics week',
    label: 'Политика: Панорама за неделю',
    emoji: '📅',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Краткое недельное резюме по контурам за 7 дней с кнопками перехода в треды кураторов',
    targetThreadKeyword: 'Политическая коллегия',
    targetAgent: 'political-group',
    defaultPrompt: '/politics week',
    isPopular: false,
    tags: ['политика', 'неделя', 'панорама', 'тренды', 'недельный срез'],
  },
  {
    id: 'cmd-politics-month',
    command: '/politics month',
    label: 'Политика: Панорама за месяц',
    emoji: '🗓️',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Стратегический срез за 30 дней: законы РФ, санкции, рынки, Ближний Восток и мировая повестка',
    targetThreadKeyword: 'Политическая коллегия',
    targetAgent: 'political-group',
    defaultPrompt: '/politics month',
    isPopular: false,
    tags: ['политика', 'месяц', 'стратегия', 'макротренды'],
  },
  {
    id: 'cmd-it',
    command: '/it',
    label: 'IT & AI Группа (Акация, Саймон, Presijo)',
    emoji: '⚡',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Перенаправляет в тред IT & AI Группы: Акация IT (Hi-Tech, девайсы), Саймон (Хабр) и Presijo AI & IT (инструменты, библиотеки, Telegram)',
    targetThreadKeyword: 'IT & AI',
    targetAgent: 'tech-group',
    defaultPrompt: '/it today',
    isPopular: true,
    tags: ['it', 'ai', 'нейросети', 'хабр', 'инструменты', 'технологии', 'окация', 'саймон', 'пресижо'],
  },
  {
    id: 'cmd-it-today',
    command: '/it today',
    label: 'IT & AI: Срез на сегодня',
    emoji: '⚡',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Оперативный IT-срез за день: девайсы, разбор публикаций с Habr и свежие AI-инструменты',
    targetThreadKeyword: 'IT & AI',
    targetAgent: 'tech-group',
    defaultPrompt: '/it today',
    isPopular: false,
    tags: ['it', 'ai', 'сегодня', 'срез', 'нейросети', 'хабр'],
  },
  {
    id: 'cmd-it-week',
    command: '/it week',
    label: 'IT & AI: Панорама за неделю',
    emoji: '📅',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Недельный дайджест технологий: Hi-Tech анонсы, топ статей Хабра и релизы библиотек',
    targetThreadKeyword: 'IT & AI',
    targetAgent: 'tech-group',
    defaultPrompt: '/it week',
    isPopular: false,
    tags: ['it', 'ai', 'неделя', 'панорама', 'технологии'],
  },
  {
    id: 'cmd-it-month',
    command: '/it month',
    label: 'IT & AI: Панорама за месяц',
    emoji: '🗓️',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Стратегический срез за 30 дней: тренды индустрии, сдвиги в BigTech и регулирование',
    targetThreadKeyword: 'IT & AI',
    targetAgent: 'tech-group',
    defaultPrompt: '/it month',
    isPopular: false,
    tags: ['it', 'ai', 'месяц', 'стратегия', 'bigtech'],
  },
  {
    id: 'cmd-tech-base',
    command: '/tech',
    label: 'IT & AI Группа (/tech)',
    emoji: '⚡',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Алиас команды /it: сводный технологический деск IT & AI Группы',
    targetThreadKeyword: 'IT & AI',
    targetAgent: 'tech-group',
    defaultPrompt: '/tech today',
    isPopular: true,
    tags: ['tech', 'it', 'ai', 'технологии'],
  },
  {
    id: 'cmd-breaking',
    command: '/breaking',
    label: 'Breaking News: Мировой пульс',
    emoji: '🔥',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в тред Breaking News: экстренные мировые молнии, виральные тренды и срочные новости',
    targetThreadKeyword: 'Breaking',
    targetAgent: 'alex-vector',
    defaultPrompt: '/breaking today',
    isPopular: true,
    tags: ['breaking', 'новости', 'пульс', 'горячие новости', 'молния', 'мир', 'алекс'],
  },
  {
    id: 'cmd-breaking-today',
    command: '/breaking today',
    label: 'Breaking News: Срез на сегодня',
    emoji: '🔥',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Экстренные мировые молнии, виральные тренды и срочные новости за сегодня',
    targetThreadKeyword: 'Breaking',
    targetAgent: 'alex-vector',
    defaultPrompt: '/breaking today',
    isPopular: false,
    tags: ['breaking', 'сегодня', 'срез', 'пульс', 'молния'],
  },
  {
    id: 'cmd-breaking-week',
    command: '/breaking week',
    label: 'Breaking News: Панорама за неделю',
    emoji: '📅',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Недельная хроника самых горячих событий, мировых происшествий и трендов',
    targetThreadKeyword: 'Breaking',
    targetAgent: 'alex-vector',
    defaultPrompt: '/breaking week',
    isPopular: false,
    tags: ['breaking', 'неделя', 'панорама', 'новости', 'пульс'],
  },
  {
    id: 'cmd-breaking-month',
    command: '/breaking month',
    label: 'Breaking News: Панорама за месяц',
    emoji: '🗓️',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Ключевые мировые события и breaking-хроника за 30 дней',
    targetThreadKeyword: 'Breaking',
    targetAgent: 'alex-vector',
    defaultPrompt: '/breaking month',
    isPopular: false,
    tags: ['breaking', 'месяц', 'хроника', 'новости'],
  },
  {
    id: 'cmd-survey-hub',
    command: '/survey',
    label: 'Координатор Опросов (Диспетчер)',
    emoji: '🧭',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Перенаправляет в тред Координатора Опросов: запуск анкетирования кураторов за день или неделю',
    targetThreadKeyword: 'Координатор Опросов',
    targetAgent: 'survey-coordinator',
    defaultPrompt: 'Опросчик, собери позиции всех кураторов по главным событиям на сегодняшнюю дату и выдели узлы пересечения.',
    isPopular: false,
    tags: ['опрос', 'кураторы', 'координатор', 'анкетирование'],
  },
  {
    id: 'cmd-sidework-hub',
    command: '/sidework',
    label: 'Продюсер Сайд-Работы (Контент & Медиа)',
    emoji: '🎨',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Перенаправляет в тред Сайд-Работы: генерация готовых постов, медиа-промптов и экспертных комментариев',
    targetThreadKeyword: 'Продюсер Сайд-Работы',
    targetAgent: 'sidework-producer',
    defaultPrompt: 'Сайд-воркер, подготовь структурированный пост/дайджест для публикации с ключевыми выводами.',
    isPopular: false,
    tags: ['сайд', 'контент', 'медиа', 'пост', 'публикация'],
  },
  {
    id: 'cmd-ivan-rf',
    command: '/ivan',
    label: 'Иван Белый: Внутренний контур РФ',
    emoji: '🇷🇺',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в персональный тред Ивана Белого: Госдума, Правительство, ЦБ РФ, ФАС, налоги и ЕДГ-2026',
    targetThreadKeyword: 'Иван Белый',
    targetAgent: 'ivan-bely',
    defaultPrompt: 'Иван, какие ключевые события, законы и решения регуляторов в РФ актуальны на сегодня?',
    isPopular: false,
    tags: ['иван', 'рф', 'правительство', 'цб', 'госдума', 'законы'],
  },
  {
    id: 'cmd-kirk-intl',
    command: '/kirk',
    label: 'Kirk Kitten: Внешний контур & Рынки',
    emoji: '🌐',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в персональный тред Kirk Kitten: санкции OFAC, ЕС, танкерный фрахт и мировые сырьевые рынки',
    targetThreadKeyword: 'Kirk Kitten',
    targetAgent: 'kirk-kitten',
    defaultPrompt: 'Kirk, какие последние сигналы по санкциям OFAC, ЕС, морской логистике и мировым рынкам?',
    isPopular: false,
    tags: ['kirk', 'санкции', 'ofac', 'ес', 'фрахт', 'нефть'],
  },
  {
    id: 'cmd-chen-asia',
    command: '/chen',
    label: 'Чэнь Вэй: АТР, Китай & БРИКС',
    emoji: '🇨🇳',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в персональный тред Чэнь Вэя: Китай, АТР, порты Нинбо/Шанхая, расчеты в нацвалютах и БРИКС',
    targetThreadKeyword: 'Чэнь Вэй',
    targetAgent: 'chen-wei',
    defaultPrompt: 'Чэнь, какие ключевые сигналы по Китаю, торговым коридорам, расчетам в нацвалютах и БРИКС актуальны на сегодня?',
    isPopular: false,
    tags: ['чэнь', 'китай', 'брикс', 'атр', 'юань', 'логистика'],
  },
  {
    id: 'cmd-okatsiya-direct',
    command: '/okatsiya',
    label: 'Акация IT: Hi-Tech & Анонсы',
    emoji: '⚡',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Переход в персональный диалог с Акацией IT: новости Hi-Tech, релизы новых девайсов, громкие анонсы BigTech, архитектура',
    targetThreadKeyword: 'Акация',
    targetAgent: 'okatsiya',
    defaultPrompt: 'Акация, какие свежие Hi-Tech анонсы, новинки девайсов и архитектурные сдвиги актуальны на сегодня?',
    isPopular: true,
    tags: ['акация', 'okatsiya', 'hitech', 'девайсы', 'анонсы', 'чипы', 'архитектура'],
  },
  {
    id: 'cmd-akatsiya-alias',
    command: '/akatsiya',
    label: 'Акация IT: Hi-Tech & Анонсы (/akatsiya)',
    emoji: '⚡',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Алиас команды /okatsiya: новости Hi-Tech, новые девайсы и громкие анонсы индустрии',
    targetThreadKeyword: 'Акация',
    targetAgent: 'okatsiya',
    defaultPrompt: 'Акация, какие свежие Hi-Tech анонсы, новинки девайсов и архитектурные сдвиги актуальны на сегодня?',
    isPopular: false,
    tags: ['акация', 'akatsiya', 'hitech', 'девайсы'],
  },
  {
    id: 'cmd-simon-direct',
    command: '/simon',
    label: 'Саймон: Разбор новостей с Habr',
    emoji: '📟',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Переход в персональный тред Саймона: разбор публикаций и инженерных статей с Habr, схемотехника, опыт сообщества',
    targetThreadKeyword: 'Саймон',
    targetAgent: 'simon-habr',
    defaultPrompt: 'Саймон, что интересного на Хабре? Разбери практические статьи сообщества и поделись выводами.',
    isPopular: true,
    tags: ['саймон', 'simon', 'хабр', 'habr', 'статьи', 'разбор', 'сообщество'],
  },
  {
    id: 'cmd-presijo-direct',
    command: '/presijo',
    label: 'Presijo AI & IT: Инструменты & Telegram',
    emoji: '🚀',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Переход в персональный тред Presijo AI & IT: новости AI-индустрии, новые инструменты, библиотеки, мониторинг Telegram-каналов',
    targetThreadKeyword: 'Presijo',
    targetAgent: 'presijo-ai',
    defaultPrompt: 'Presijo, какие новые AI-инструменты появились на рынке, какие свежие фичи и релизы библиотек заслуживают внимания?',
    isPopular: true,
    tags: ['presijo', 'пресижо', 'ai', 'инструменты', 'tools', 'библиотеки', 'telegram'],
  },
  {
    id: 'cmd-alex-pulse',
    command: '/alex',
    label: 'Breaking News: Мировой пульс (/alex)',
    emoji: '🔥',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Алиас для перехода в тред Breaking News: экстренные мировые молнии, виральные тренды и срочные новости',
    targetThreadKeyword: 'Breaking',
    targetAgent: 'alex-vector',
    defaultPrompt: '/breaking today',
    isPopular: false,
    tags: ['алекс', 'breaking', 'пульс', 'горячие новости', 'молния', 'мир'],
  },
  {
    id: 'cmd-marcus-domino',
    command: '/marcus',
    label: 'Маркус Вейн: Эффект домино & Ветвление',
    emoji: '♟️',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в тред Маркуса Вейна: анализ точек бифуркации, вакуума силы и построение дерева смежных веток',
    targetThreadKeyword: 'Маркус Вейн',
    targetAgent: 'marcus-vane',
    defaultPrompt: 'Маркус, разбери потенциал ветвления текущих событий и покажи, какие смежные контуры окажутся под ударом.',
    isPopular: true,
    tags: ['маркус', 'домино', 'ветвление', 'бифуркация', 'каскад', 'bpi'],
  },
  {
    id: 'cmd-tariq-mena',
    command: '/tariq',
    label: 'Тарик Саид: Ближний Восток & Залив',
    emoji: '🕌',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в персональный тред Тарика Саида: Ирак, Иран, монархии Залива, Левант, военные базы и безопасность MENA',
    targetThreadKeyword: 'Тарик Саид',
    targetAgent: 'tariq-said',
    defaultPrompt: 'Тарик, какова оперативная обстановка на Ближнем Востоке, вокруг Ирака и в зоне Персидского залива?',
    isPopular: true,
    tags: ['тарик', 'ближний восток', 'ирак', 'залив', 'иран', 'mena'],
  },
  {
    id: 'cmd-helena-energy',
    command: '/helena',
    label: 'Хелена Брандт: Сырье & Морские артерии',
    emoji: '⚓',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в тред Хелены Брандт: котировки Brent/WTI, ставки военного фрахта Lloyd\'s, проливы Ормуз и Суэц',
    targetThreadKeyword: 'Хелена Брандт',
    targetAgent: 'helena-brandt',
    defaultPrompt: 'Хелена, как текущие геополитические сдвиги отражаются на нефтяных котировках, фрахте танкеров и проливах?',
    isPopular: true,
    tags: ['хелена', 'нефть', 'сырье', 'пролив', 'ормуз', 'фрахт', 'логистика'],
  },
  {
    id: 'cmd-hot-pulse-group',
    command: '/survey-breaking',
    label: 'Группа быстрого реагирования (Пульс)',
    emoji: '🔥',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в коллегию быстрого реагирования: Алекс Вектор, Kirk Kitten, Маркус Вейн',
    targetThreadKeyword: 'Группа быстрого реагирования',
    targetAgent: 'hot-pulse-group',
    defaultPrompt: '/survey-breaking Опроси группу быстрого реагирования по экстренной повестке',
    isPopular: true,
    tags: ['пульс', 'breaking', 'молния', 'экспресс'],
  },
  {
    id: 'cmd-domino-nexus-group',
    command: '/survey-nexus',
    label: 'Коллегия каскадных рисков & Ветвления',
    emoji: '♟️',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в коллегию прогнозирования эффекта домино: Маркус Вейн, Тарик Саид, Хелена Брандт, Чэнь Вэй',
    targetThreadKeyword: 'Коллегия каскадных рисков',
    targetAgent: 'domino-nexus-group',
    defaultPrompt: '/survey-nexus Опроси коллегию каскадных рисков по эффекту домино и точкам ветвления',
    isPopular: true,
    tags: ['домино', 'nexus', 'каскад', 'ветвление'],
  },
  {
    id: 'cmd-mena-security-group',
    command: '/survey-mena',
    label: 'Консилиум Ближнего Востока & Юга',
    emoji: '🕌',
    type: 'REDIRECT',
    category: 'REDIRECT',
    description: 'Переход в консилиум Ближнего Востока: Тарик Саид, Иван Белый, Kirk Kitten, Хелена Брандт',
    targetThreadKeyword: 'Консилиум Ближнего Востока',
    targetAgent: 'mena-security-group',
    defaultPrompt: '/survey-mena Опроси консилиум Ближнего Востока и зоны Залива',
    isPopular: true,
    tags: ['ближний восток', 'mena', 'залив', 'ормуз'],
  },

  // =========================================================================
  // 2. ВСПОМОГАТЕЛЬНЫЕ КОМАНДЫ (ДОСТУПНЫ В ЛЮБОМ ЧАТЕ С АГЕНТАМИ)
  // =========================================================================
  {
    id: 'cmd-survey-today',
    command: '/survey-today',
    label: 'Опрос: Срез на сегодня',
    emoji: '🧭',
    type: 'AUXILIARY',
    category: 'SURVEY',
    description: 'Вспомогательная команда в любом чате: экспресс-опрос кураторов по событиям на выбранную дату',
    targetAgent: 'survey-coordinator',
    defaultPrompt: 'Опросчик, собери позиции всех кураторов по главным событиям на сегодняшнюю дату и выдели узлы пересечения.',
    isPopular: true,
    tags: ['опрос', 'сегодня', 'срез', 'координатор'],
  },
  {
    id: 'cmd-survey-yesterday',
    command: '/survey-yesterday',
    label: 'Опрос: Срез за вчера',
    emoji: '⏪',
    type: 'AUXILIARY',
    category: 'SURVEY',
    description: 'Вспомогательная команда в любом чате: опрос кураторов по событиям за вчерашний день',
    targetAgent: 'survey-coordinator',
    defaultPrompt: 'Опросчик, опроси группу политических кураторов и Окацию по событиям за вчерашний день.',
    isPopular: false,
    tags: ['опрос', 'вчера', 'ретроспектива'],
  },
  {
    id: 'cmd-survey-week',
    command: '/survey-week',
    label: 'Опрос: Панорама за неделю',
    emoji: '📊',
    type: 'AUXILIARY',
    category: 'SURVEY',
    description: 'Вспомогательная команда в любом чате: 7-дневный аналитический срез с долгосрочными трендами',
    targetAgent: 'survey-coordinator',
    defaultPrompt: 'Опросчик, проведи комплексный опрос всех кураторов по ключевым сюжетам и трендам за последние 7 дней.',
    isPopular: false,
    tags: ['опрос', 'неделя', 'тренды', 'аналитика'],
  },
  {
    id: 'cmd-media',
    command: '/media',
    label: 'AI-Медиа & Схемы Mermaid',
    emoji: '🎨',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Вспомогательная команда в любом чате: генерация промптов для DALL-E / Midjourney и блок-схем Mermaid',
    targetAgent: 'sidework-producer',
    defaultPrompt: 'Сайд-воркер, сгенерируй профессиональные промпты для иллюстраций (DALL-E / Midjourney) и составь диаграмму связей Mermaid для этой темы.',
    isPopular: true,
    tags: ['медиа', 'dalle', 'midjourney', 'mermaid', 'схемы', 'визуал'],
  },
  {
    id: 'cmd-comment',
    command: '/comment',
    label: 'Экспертный комментарий & Фактчек',
    emoji: '💬',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Вспомогательная команда в любом чате: дополнение материалов комментариями кураторов и фактчеком',
    targetAgent: 'sidework-producer',
    defaultPrompt: 'Сайд-воркер, дополни собранные материалы аналитическим комментарием кураторов и фактологической справкой.',
    isPopular: false,
    tags: ['комментарий', 'фактчек', 'эксперт', 'проверка'],
  },
  {
    id: 'cmd-sidework-post',
    command: '/sidework-post',
    label: 'Создать пост / Дайджест',
    emoji: '📝',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Вспомогательная команда в любом чате: формирование готового текста публикации для Obsidian или Telegram',
    targetAgent: 'sidework-producer',
    defaultPrompt: 'Сайд-воркер, на основе последних собранных данных подготовь структурированный пост/дайджест для публикации с ключевыми выводами.',
    isPopular: true,
    tags: ['пост', 'дайджест', 'статья', 'публикация', 'obsidian'],
  },
  {
    id: 'cmd-post-today',
    command: '/post today',
    label: 'Telegram Post: Сводка за день',
    emoji: '✈️',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Вывод сводки куратора за сегодня в формате Telegram-поста с тегами, буллетами и действиями',
    defaultPrompt: '/post today',
    isPopular: true,
    tags: ['telegram', 'post', 'тг', 'пост', 'сегодня', 'сводка'],
  },
  {
    id: 'cmd-post-week',
    command: '/post week',
    label: 'Telegram Post: Дайджест недели',
    emoji: '📅',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Вывод дайджеста куратора за неделю в формате Telegram-поста с ключевыми итогами',
    defaultPrompt: '/post week',
    isPopular: true,
    tags: ['telegram', 'post', 'тг', 'пост', 'неделя', 'дайджест'],
  },
  {
    id: 'cmd-tg-today',
    command: '/tg today',
    label: 'TG Пост за сегодня',
    emoji: '✈️',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Короткий алиас для формирования Telegram-поста за текущие сутки',
    defaultPrompt: '/tg today',
    isPopular: false,
    tags: ['tg', 'тг', 'пост', 'сегодня'],
  },
  {
    id: 'cmd-tg-week',
    command: '/tg week',
    label: 'TG Дайджест за неделю',
    emoji: '📅',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Короткий алиас для формирования Telegram-дайджеста за 7 дней',
    defaultPrompt: '/tg week',
    isPopular: false,
    tags: ['tg', 'тг', 'дайджест', 'неделя'],
  },
  {
    id: 'cmd-harvest',
    command: '/harvest',
    label: 'Харвестер: Сбор сырых сигналов',
    emoji: '📡',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Вспомогательная команда в любом чате: проверка входящих фидов и поиск новых инфоповодов',
    targetAgent: 'harvester-agent',
    defaultPrompt: 'Харвестер, выполни проверку входящих фидов и источников, собери свежие сигналы для передачи кураторам.',
    isPopular: false,
    tags: ['харвестер', 'сбор', 'источники', 'фиды', 'новости'],
  },
  {
    id: 'cmd-tech-ai',
    command: '/ai',
    label: 'Окация: Только AI & LLM',
    emoji: '🧠',
    type: 'AUXILIARY',
    category: 'TECH',
    description: 'Вспомогательная команда: выделение новостей исключительно по AI, LLM, весам и архитектурам моделей',
    targetAgent: 'okatsiya',
    defaultPrompt: 'Окация, выдели исключительно новости и прорывы в сфере AI, LLM, нейросетей и машинного обучения на сегодня.',
    isPopular: true,
    tags: ['ai', 'llm', 'нейросети', 'модели', 'окация'],
  },
  {
    id: 'cmd-tech-devops',
    command: '/devops',
    label: 'Окация: DevOps & Cloud',
    emoji: '🚢',
    type: 'AUXILIARY',
    category: 'TECH',
    description: 'Вспомогательная команда: Kubernetes, облачные сервисы, CI/CD, отказоустойчивость и SRE',
    targetAgent: 'okatsiya',
    defaultPrompt: 'Окация, какова обстановка в инфраструктуре, Kubernetes, CI/CD, контейнерах и облачных платформах?',
    isPopular: false,
    tags: ['devops', 'kubernetes', 'sre', 'ci/cd', 'cloud', 'инфраструктура'],
  },
  {
    id: 'cmd-tech-backend',
    command: '/backend',
    label: 'Окация: Backend & HighLoad',
    emoji: '⚙️',
    type: 'AUXILIARY',
    category: 'TECH',
    description: 'Вспомогательная команда: распределенные системы, базы данных, Go/Rust/Java и высоконагруженные сервисы',
    targetAgent: 'okatsiya',
    defaultPrompt: 'Окация, какие ключевые обновления в бэкенде, распределенных системах, базах данных и системных языках?',
    isPopular: false,
    tags: ['backend', 'бэкенд', 'базы данных', 'highload', 'микросервисы'],
  },
  {
    id: 'cmd-tech-bigtech',
    command: '/bigtech',
    label: 'Окация: BigTech & Корпорации',
    emoji: '🏢',
    type: 'AUXILIARY',
    category: 'TECH',
    description: 'Вспомогательная команда: рыночные маневры IT-гигантов (Nvidia, Apple, Google, Microsoft) и антитраст',
    targetAgent: 'okatsiya',
    defaultPrompt: 'Окация, что происходит у технологических гигантов (BigTech), антимонопольных регуляторов и на IT-рынках?',
    isPopular: false,
    tags: ['bigtech', 'nvidia', 'apple', 'google', 'microsoft', 'акции'],
  },
  {
    id: 'cmd-tech-infosec',
    command: '/infosec',
    label: 'Окация: InfoSec & Уязвимости',
    emoji: '🛡️',
    type: 'AUXILIARY',
    category: 'TECH',
    description: 'Вспомогательная команда: кибербезопасность, 0-day уязвимости, патчи и аудит защищенности',
    targetAgent: 'okatsiya',
    defaultPrompt: 'Окация, какие критические уязвимости CVE, инциденты информационной безопасности и патчи зафиксированы?',
    isPopular: false,
    tags: ['infosec', 'безопасность', 'уязвимости', 'cve', 'хакеры'],
  },
  {
    id: 'cmd-curator-german',
    command: '/german',
    label: 'Герман: Habr, Хакер & Своя кухня',
    emoji: '📟',
    type: 'REDIRECT',
    category: 'TECH',
    description: 'Инженерная оптика IT-сообщества: просмотр Habr, журнала «Хакер» и формирование тематических Note',
    targetAgent: 'german-kernel',
    defaultPrompt: 'Герман, что интересного на Хабре и в материалах «Хакера»? Разбери статьи и сгруппируй темы для заметки.',
    isPopular: true,
    tags: ['герман', 'хабр', 'habr', 'хакер', 'xakep', 'it', 'олдскул', 'статьи', 'note'],
  },
  {
    id: 'cmd-curator-habr',
    command: '/habr',
    label: 'Герман: Разбор публикаций Habr',
    emoji: '📝',
    type: 'AUXILIARY',
    category: 'TECH',
    description: 'Мониторинг публикаций Хабра: поиск глубоких инженерных статей, разбор старых плат и создание Note',
    targetAgent: 'german-kernel',
    defaultPrompt: 'Герман, сделай выборку свежих статей с Habr, выдели олдскульные темы и структурируй выводы в Note.',
    isPopular: false,
    tags: ['habr', 'хабр', 'статьи', 'разборы', 'олдскул', 'платы'],
  },
  {
    id: 'cmd-curator-xakep',
    command: '/xakep',
    label: 'Герман: Выпуск журнала «Хакер»',
    emoji: '🏴‍☠️',
    type: 'AUXILIARY',
    category: 'TECH',
    description: 'Разбор номера журнала Хакер (xakep.ru), группировка по темам и сборка Super Note для NotebookLM',
    targetAgent: 'german-kernel',
    defaultPrompt: 'Герман, покажи разбор материалов журнала «Хакер», выдели темы выпуска и подготовь Super Note под создание NotebookLM.',
    isPopular: false,
    tags: ['xakep', 'хакер', 'журнал', 'кибербез', 'super-note', 'контейнер'],
  },
  {
    id: 'cmd-worker-notebook',
    command: '/notebook',
    label: 'NotebookLM: Фоновый дневник',
    emoji: '📓',
    type: 'AUXILIARY',
    category: 'CONTENT',
    description: 'Агент создания дневников NotebookLM: фоновая генерация подкаста с расчетом времени и автообновлением Note',
    targetAgent: 'notebook-producer',
    defaultPrompt: 'NotebookLM Агент, возьми подготовленную Super Note и начни создание дневника и подкаста в фоне с расчетом ETA.',
    isPopular: true,
    tags: ['notebook', 'notebooklm', 'подкаст', 'дневник', 'фоновая-задача', 'eta'],
  },
];
