import { Note, NoteType } from '@lenta/shared';
import { createTag, createHashtag } from './types';

// --- 3. ORTHODOX CHRISTIAN LITURGICAL CALENDAR 2026 ---
export const ORTHODOX_NOTES: Note[] = [
  {
    id: 'orth-1',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Рождество Господа Бога и Спаса нашего Иисуса Христа',
    description: `### 7 Января — Двунадесятый господский праздник
Один из величайших праздников Православной Церкви. Торжественные ночные богослужения во всех храмах и соборах, славление Христа и начало святочных дней.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-01-07T00:00:00.000Z',
    endDate: '2026-01-07T23:59:59.000Z',
    icon: 'star',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'star')],
    hashtags: [createHashtag('ht-orth-1', 'РождествоХристово'), createHashtag('ht-orth-2', 'Православие')],
    createdAt: '2026-01-07T00:00:00.000Z',
    updatedAt: '2026-01-07T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://patriarchia.ru',
  },
  {
    id: 'orth-2',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Святое Богоявление (Крещение Господне)',
    description: `### 19 Января — Крещение Спасителя в водах Иордана
Великое водоосвящение (Великая агиасма), традиционные крещенские купания в освященных иорданях и явление Святой Троицы.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-01-19T06:00:00.000Z',
    endDate: null,
    icon: 'droplet',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'droplet')],
    hashtags: [createHashtag('ht-orth-3', 'КрещениеГосподне'), createHashtag('ht-orth-4', 'Богоявление')],
    createdAt: '2026-01-19T00:00:00.000Z',
    updatedAt: '2026-01-19T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-3',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Сретение Господне',
    description: `### 15 Февраля — Встреча Ветхого и Нового Заветов
Принесение Богомладенца Иисуса в Иерусалимский храм на сороковой день по Рождестве и встреча праведным старцем Симеоном и пророчицей Анной. День православной молодежи.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-15T08:00:00.000Z',
    endDate: null,
    icon: 'sparkles',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'sparkles')],
    hashtags: [createHashtag('ht-orth-5', 'СретениеГосподне')],
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: '2026-02-15T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-4',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Вход Господень в Иерусалим (Вербное воскресенье)',
    description: `### 5 Апреля 2026 — Неделя 6-я Великого поста
Торжественный вход Спасителя в священный город Иерусалим накануне крестных страданий. Освящение веточек вербы в воспоминание пальмовых ветвей.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-04-05T08:00:00.000Z',
    endDate: null,
    icon: 'feather',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'feather')],
    hashtags: [createHashtag('ht-orth-6', 'ВербноеВоскресенье')],
    createdAt: '2026-04-05T00:00:00.000Z',
    updatedAt: '2026-04-05T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-5',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Благовещение Пресвятой Богородицы',
    description: `### 7 Апреля
Возвещение архангелом Гавриилом Деве Марии благой вести о непорочном зачатии и рождении Спасителя мира Иисуса Христа. Древний обычай выпускать на волю белых птиц.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-04-07T08:00:00.000Z',
    endDate: null,
    icon: 'sun',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'sun')],
    hashtags: [createHashtag('ht-orth-7', 'Благовещение')],
    createdAt: '2026-04-07T00:00:00.000Z',
    updatedAt: '2026-04-07T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-6',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Светлое Христово Воскресение — ПАСХА',
    description: `### 12 Апреля 2026 г. — Праздников Праздник и Торжество из Торжеств
Главное событие церковного года Православной Церкви. Победа Спасителя над смертью и адом. Доставка Благодатного Огня из Иерусалима, крестные ходы, освящение куличей, пасох и крашеных яиц.

> **«Христос Воскресе! — Воистину Воскресе!»**`,
    type: 'EVENT' as NoteType,
    startDate: '2026-04-12T00:00:00.000Z',
    endDate: '2026-04-12T23:59:59.000Z',
    icon: 'sparkles',
    tags: [createTag('tax-orth-2', 'Пасхальный цикл', 'church.orthodox.easter', 'sparkles')],
    hashtags: [createHashtag('ht-orth-8', 'Пасха2026'), createHashtag('ht-orth-9', 'ХристосВоскресе')],
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: '2026-04-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://patriarchia.ru',
  },
  {
    id: 'orth-7',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Вознесение Господне',
    description: `### 21 Мая 2026 г. (40-й день по Пасхе)
Праздник в память о восшествии Господа Иисуса Христа во плоти на Небо на горе Елеон в присутствии Богородицы и апостолов.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-21T08:00:00.000Z',
    endDate: null,
    icon: 'cloud',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'cloud')],
    hashtags: [createHashtag('ht-orth-10', 'ВознесениеГосподне')],
    createdAt: '2026-05-21T00:00:00.000Z',
    updatedAt: '2026-05-21T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-8',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'День Святой Троицы (Пятидесятница)',
    description: `### 31 Мая 2026 г. (50-й день по Пасхе)
Сошествие Святого Духа на апостолов в Сионской горнице. День рождения Церкви Христовой. Храмы украшаются свежими ветвями берез и весенней зеленью.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-31T08:00:00.000Z',
    endDate: null,
    icon: 'feather',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'feather')],
    hashtags: [createHashtag('ht-orth-11', 'Троица'), createHashtag('ht-orth-12', 'Пятидесятница')],
    createdAt: '2026-05-31T00:00:00.000Z',
    updatedAt: '2026-05-31T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-9',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Успение Пресвятой Богородицы',
    description: `### 28 Августа — Окончание Успенского поста
Блаженная кончина Божией Матери, взятие Ее пречистого тела и души на Небеса Господом Иисусом Христом. Чин погребения Плащаницы Богородицы.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-08-28T08:00:00.000Z',
    endDate: null,
    icon: 'bookmark',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'bookmark')],
    hashtags: [createHashtag('ht-orth-13', 'УспениеБогородицы')],
    createdAt: '2026-08-28T00:00:00.000Z',
    updatedAt: '2026-08-28T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-10',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Покров Пресвятой Богородицы',
    description: `### 14 Октября — Великий праздник
Воспоминание явления Богоматери святому Андрею Юродивому во Влахернском храме Константинополя, распростершей Свой омофор в защиту молящихся.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-10-14T08:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-orth-3', 'Великие праздники', 'church.orthodox.feasts', 'shield')],
    hashtags: [createHashtag('ht-orth-14', 'ПокровБогородицы')],
    createdAt: '2026-10-14T00:00:00.000Z',
    updatedAt: '2026-10-14T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];

// --- 4. CATHOLIC CHRISTIAN LITURGICAL CALENDAR 2026 ---
export const CATHOLIC_NOTES: Note[] = [
  {
    id: 'cath-1',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Богоявление (День трех королей)',
    description: `### 6 Января — Epiphania Domini
Поклонение волхвов (Каспара, Мельхиора и Бальтазара) Младенцу Иисусу. Традиция мелом писать на дверях инициалы «C + M + B 2026».`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-01-06T08:00:00.000Z',
    endDate: null,
    icon: 'crown',
    tags: [createTag('tax-cath-1', 'Католические торжества', 'church.catholic.solemnities', 'crown')],
    hashtags: [createHashtag('ht-cath-1', 'Богоявление'), createHashtag('ht-cath-2', 'ТриКороля')],
    createdAt: '2026-01-06T00:00:00.000Z',
    updatedAt: '2026-01-06T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://vatican.va',
  },
  {
    id: 'cath-2',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Пепельная среда (Начало Великого поста)',
    description: `### 18 Февраля 2026 г. — Dies Cinerum
Начало 40-дневного Великого поста (Quadragesima) в латинском обряде. Обряд посыпания голов освященным пеплом: «Помни, что ты прах, и в прах возвратишься».`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-18T08:00:00.000Z',
    endDate: null,
    icon: 'cross',
    tags: [createTag('tax-cath-2', 'Великий пост', 'church.catholic.lent', 'cross')],
    hashtags: [createHashtag('ht-cath-3', 'ПепельнаяСреда'), createHashtag('ht-cath-4', 'ВеликийПост')],
    createdAt: '2026-02-18T00:00:00.000Z',
    updatedAt: '2026-02-18T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'cath-3',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Пасхальное триденствие: Страстная пятница',
    description: `### 3 Апреля 2026 г. — Good Friday
Воспоминание крестной смерти Спасителя на Голгофе. Поклонение Святому Кресту, тишина алтаря и молитва у Гроба Господня.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-04-03T15:00:00.000Z',
    endDate: '2026-04-03T23:59:59.000Z',
    icon: 'cross',
    tags: [createTag('tax-cath-3', 'Пасхальное триденствие', 'church.catholic.triduum', 'cross')],
    hashtags: [createHashtag('ht-cath-5', 'СтрастнаяПятница'), createHashtag('ht-cath-6', 'Triduum')],
    createdAt: '2026-04-03T00:00:00.000Z',
    updatedAt: '2026-04-03T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'cath-4',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Светлое Христово Воскресение — Католическая Пасха',
    description: `### 5 Апреля 2026 г. — Dominica Resurrectionis
Главное торжество католического литургического года. Ночная Пасхальная вигилия, зажжение Пасхала и апостольское благословение Папы Римского «Urbi et Orbi» («Граду и Миру»).`,
    type: 'EVENT' as NoteType,
    startDate: '2026-04-05T00:00:00.000Z',
    endDate: '2026-04-05T23:59:59.000Z',
    icon: 'sun',
    tags: [createTag('tax-cath-1', 'Католические торжества', 'church.catholic.solemnities', 'sun')],
    hashtags: [createHashtag('ht-cath-7', 'Пасха2026'), createHashtag('ht-cath-8', 'UrbiEtOrbi')],
    createdAt: '2026-04-05T00:00:00.000Z',
    updatedAt: '2026-04-05T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://vatican.va',
  },
  {
    id: 'cath-5',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Торжество Пресвятого Тела и Крови Христа (Corpus Christi)',
    description: `### 4 Июня 2026 г. (Четверг после Троицы)
Праздник евхаристического благодарения. Торжественные процессии со Святыми Дарами по улицам городов и украшение алтарей живыми цветами.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-06-04T09:00:00.000Z',
    endDate: null,
    icon: 'cup',
    tags: [createTag('tax-cath-1', 'Католические торжества', 'church.catholic.solemnities', 'cup')],
    hashtags: [createHashtag('ht-cath-9', 'CorpusChristi'), createHashtag('ht-cath-10', 'Евхаристия')],
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'cath-6',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Рождество Христово (Christmas)',
    description: `### 25 Декабря — Sollemnitas in Nativitate Domini
Главный зимний праздник латинского обряда. Ночная месса («Пастырка»), вертепы в базиликах и прославление рождения Спасителя.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-12-25T00:00:00.000Z',
    endDate: '2026-12-25T23:59:59.000Z',
    icon: 'star',
    tags: [createTag('tax-cath-1', 'Католические торжества', 'church.catholic.solemnities', 'star')],
    hashtags: [createHashtag('ht-cath-11', 'Christmas'), createHashtag('ht-cath-12', 'Рождество')],
    createdAt: '2026-12-25T00:00:00.000Z',
    updatedAt: '2026-12-25T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://vatican.va',
  },
];

// --- 5. ISLAMIC RELIGIOUS CALENDAR (HIJRI 1447–1448) ---
export const ISLAMIC_NOTES: Note[] = [
  {
    id: 'isl-1',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Начало священного месяца Рамадан 1447 г. хиджры',
    description: `### 18 Февраля 2026 г. — Священный месяц поста
Начало девятого месяца мусульманского лунного календаря. Время строгого поста (ураза) от рассвета (фаджр) до заката (магриб), чтения Священного Корана, совершения молитв таравих и благотворительности.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-02-18T00:00:00.000Z',
    endDate: '2026-03-19T23:59:59.000Z',
    icon: 'moon',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'moon')],
    hashtags: [createHashtag('ht-isl-1', 'Рамадан2026'), createHashtag('ht-isl-2', 'RamadanMubarak'), createHashtag('ht-isl-3', 'Ураза')],
    createdAt: '2026-02-18T00:00:00.000Z',
    updatedAt: '2026-02-18T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://dumrf.ru',
  },
  {
    id: 'isl-2',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Ночь могущества и предопределения (Ляйлят аль-Кадр)',
    description: `### Ночь с 15 на 16 Марта 2026 г. (27-я ночь Рамадана)
Благословенная ночь ниспослания первых аятов Священного Корана пророку Мухаммаду через ангела Джибриля. В Коране сказано, что эта ночь «лучше тысячи месяцев». Ночные бдения, дуа и мольбы.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-03-15T18:00:00.000Z',
    endDate: '2026-03-16T06:00:00.000Z',
    icon: 'sparkles',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'sparkles')],
    hashtags: [createHashtag('ht-isl-4', 'ЛяйлятальКадр'), createHashtag('ht-isl-5', 'LaylatAlQadr')],
    createdAt: '2026-03-15T00:00:00.000Z',
    updatedAt: '2026-03-15T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'isl-3',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Ураза-байрам (Ид аль-Фитр) — Праздник разговения',
    description: `### 20 Марта 2026 г. (1 Шавваль 1447 г. хиджры)
Один из двух главных праздников ислама, знаменующий окончание священного месяца Рамадан. Праздничный намаз (гаит-намаз) в мечетях, выплата милостыни закят аль-фитр, посещение родных и праздничная трапеза.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-03-20T05:00:00.000Z',
    endDate: '2026-03-20T23:59:59.000Z',
    icon: 'smile',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'smile')],
    hashtags: [createHashtag('ht-isl-6', 'УразаБайрам'), createHashtag('ht-isl-7', 'ИдальФитр'), createHashtag('ht-isl-8', 'EidMubarak')],
    createdAt: '2026-03-20T00:00:00.000Z',
    updatedAt: '2026-03-20T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://dumrf.ru',
  },
  {
    id: 'isl-4',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'День Арафа (Кульминация Хаджа)',
    description: `### 26 Мая 2026 г. (9 Зуль-хиджа 1447 г. хиджры)
Главный день паломничества в Мекку: стояние паломников в молитве на священной горе Арафат. Для мусульман, не совершающих хадж, пост в день Арафа смывает грехи прошлого и наступающего года.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-26T06:00:00.000Z',
    endDate: null,
    icon: 'mountain',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'mountain')],
    hashtags: [createHashtag('ht-isl-9', 'ДеньАрафа'), createHashtag('ht-isl-10', 'Хадж2026')],
    createdAt: '2026-05-26T00:00:00.000Z',
    updatedAt: '2026-05-26T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'isl-5',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Курбан-байрам (Ид аль-Адха) — Праздник жертвоприношения',
    description: `### 27–30 Мая 2026 г. (10–13 Зуль-хиджа 1447 г. хиджры)
Величайший праздник ислама в память о готовности пророка Ибрахима (Авраама) принести в жертву своего сына. Совершение праздничного намаза, обряд курбана (жертвоприношения), раздача мяса бедным и нуждающимся, дни ташрика.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-05-27T05:00:00.000Z',
    endDate: '2026-05-30T23:59:59.000Z',
    icon: 'heart',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'heart')],
    hashtags: [createHashtag('ht-isl-11', 'КурбанБайрам'), createHashtag('ht-isl-12', 'ИдальАдха'), createHashtag('ht-isl-13', 'EidAlAdha')],
    createdAt: '2026-05-27T00:00:00.000Z',
    updatedAt: '2026-05-27T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://dumrf.ru',
  },
  {
    id: 'isl-6',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Новый 1448 год по Хиджре (1 Мухаррам)',
    description: `### 16 Июня 2026 г. — Начало нового мусульманского года
Первый день первого месяца Мухаррам. В память о переселении (хиджре) пророка Мухаммада и первых мусульман из Мекки в Медину в 622 году н.э.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-06-16T00:00:00.000Z',
    endDate: null,
    icon: 'calendar',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'calendar')],
    hashtags: [createHashtag('ht-isl-14', 'Хиджра1448'), createHashtag('ht-isl-15', 'МусульманскийНовыйГод')],
    createdAt: '2026-06-16T00:00:00.000Z',
    updatedAt: '2026-06-16T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];

// --- 6. WORLD RELIGIONS (ISLAM, JUDAISM, BUDDHISM) ---
export const WORLD_RELIGIONS_NOTES: Note[] = [
  ...ISLAMIC_NOTES.slice(0, 3).map((n) => ({
    ...n,
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
  })),
  {
    id: 'rel-jud-1',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Пурим (Purim)',
    description: `### 3 Марта 2026 г. (14 Адара 5786 г.)
Веселый еврейский праздник в память о чудесном спасении евреев Персидской империи от козней визиря Амана, описанном в Книге Эсфирь (Мегилат Эстер). Чтение свитка, карнавальные костюмы и угощение «уши Амана» (гоменташн).`,
    type: 'EVENT' as NoteType,
    startDate: '2026-03-03T00:00:00.000Z',
    endDate: '2026-03-03T23:59:59.000Z',
    icon: 'gift',
    tags: [createTag('tax-rel-jud', 'Иудаизм', 'religion.judaism', 'star')],
    hashtags: [createHashtag('ht-rel-jud-1', 'Пурим'), createHashtag('ht-rel-jud-2', 'PurimSameach')],
    createdAt: '2026-03-03T00:00:00.000Z',
    updatedAt: '2026-03-03T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'rel-jud-2',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Песах (Еврейская Пасха) — Праздник Свободы',
    description: `### 2–9 Апреля 2026 г. (15–22 Нисана 5786 г.)
Один из главных библейских праздников в память об Исходе сынов Израиля из египетского рабства. Праздничная пасхальная трапеза Седер, чтение Агады и вкушение опресноков (мацы).`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-04-02T18:00:00.000Z',
    endDate: '2026-04-09T21:00:00.000Z',
    icon: 'sun',
    tags: [createTag('tax-rel-jud', 'Иудаизм', 'religion.judaism', 'sun')],
    hashtags: [createHashtag('ht-rel-jud-3', 'Песах'), createHashtag('ht-rel-jud-4', 'Passover')],
    createdAt: '2026-04-02T00:00:00.000Z',
    updatedAt: '2026-04-02T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'rel-jud-3',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Рош ха-Шана — Еврейский Новый 5787 год',
    description: `### 12–13 Сентября 2026 г. (1–2 Тишрея 5787 г.)
Праздник сотворения мира и день суда Всевышнего. Трубление в бараний рог (шофар), обмакивание яблок в мед с пожеланием «Сладкого и доброго Нового года» (Шана това у-метука).`,
    type: 'EVENT' as NoteType,
    startDate: '2026-09-12T00:00:00.000Z',
    endDate: '2026-09-13T23:59:59.000Z',
    icon: 'bell',
    tags: [createTag('tax-rel-jud', 'Иудаизм', 'religion.judaism', 'bell')],
    hashtags: [createHashtag('ht-rel-jud-5', 'РошХаШана'), createHashtag('ht-rel-jud-6', 'ШанаТова')],
    createdAt: '2026-09-12T00:00:00.000Z',
    updatedAt: '2026-09-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'rel-bud-1',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Сагаалган (Белый Месяц) — Буддийский Новый год',
    description: `### 18 Февраля 2026 г. — Год Огненной Лошади
Главный праздник монголо- и тюркоязычных буддийских народов России (Бурятия, Калмыкия, Тува). Очистительный молебен Дугжууба, белая пища, благопожелания старшим и духовное обновление.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-18T06:00:00.000Z',
    endDate: null,
    icon: 'sparkles',
    tags: [createTag('tax-rel-bud', 'Буддизм', 'religion.buddhism', 'sparkles')],
    hashtags: [createHashtag('ht-rel-bud-1', 'Сагаалган'), createHashtag('ht-rel-bud-2', 'БелыйМесяц'), createHashtag('ht-rel-bud-3', 'БуддизмРоссии')],
    createdAt: '2026-02-18T00:00:00.000Z',
    updatedAt: '2026-02-18T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'rel-bud-2',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Весак (Дончод-хурал) — День рождения Будды',
    description: `### 31 Мая 2026 г. (Полнолуние месяца Вайшакха)
Священный тройной праздник буддийского мира: день Рождения, Просветления (Бодхи) и ухода в Паринирвану Будды Шакьямуни. Зажжение светильников, обход храмов (гороо) и созерцание.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-31T06:00:00.000Z',
    endDate: null,
    icon: 'sun',
    tags: [createTag('tax-rel-bud', 'Буддизм', 'religion.buddhism', 'sun')],
    hashtags: [createHashtag('ht-rel-bud-4', 'Весак'), createHashtag('ht-rel-bud-5', 'ДеньБудды')],
    createdAt: '2026-05-31T00:00:00.000Z',
    updatedAt: '2026-05-31T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];
