import { Note, NoteType } from '@lenta/shared';
import { createTag, createHashtag } from './types';

// --- 1. RUSSIAN OFFICIAL STATE HOLIDAYS ---
export const RUSSIAN_OFFICIAL_NOTES: Note[] = [
  {
    id: 'ru-off-1',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'Новый 2026 Год и Новогодние каникулы',
    description: `### Празднование Нового Года в России
Официальные новогодние праздничные каникулы продлятся с 1 по 8 января 2026 года.
Главные городские ёлки, световые инсталляции и праздничные площадки открыты во всех регионах страны.

- **Даты отдыха:** 1–8 января 2026 г.
- **Статус:** Официальный государственный нерабочий праздничный день (ТК РФ ст. 112).`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-01-08T23:59:59.000Z',
    icon: 'sparkles',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-1', 'НовыйГод'), createHashtag('ht-ru-off-2', 'Праздники2026')],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://government.ru',
  },
  {
    id: 'ru-off-2',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День российского студенчества (Татьянин день)',
    description: `### 25 Января
Памятная дата России в честь основания Московского университета императрицей Елизаветой Петровной в 1755 году. День студенчества и академических традиций.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-01-25T09:00:00.000Z',
    endDate: null,
    icon: 'book-open',
    tags: [createTag('tax-ru-off-2', 'Памятные даты', 'holidays.russia.memorial', 'book')],
    hashtags: [createHashtag('ht-ru-off-3', 'ДеньСтудента'), createHashtag('ht-ru-off-4', 'ТатьянинДень')],
    createdAt: '2026-01-25T00:00:00.000Z',
    updatedAt: '2026-01-25T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-3',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День российской науки',
    description: `### 8 Февраля
В память об учреждении Петром I Академии наук в Санкт-Петербурге 8 февраля 1724 года. Чествование ученых, открытий и научно-технического суверенитета.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-08T09:00:00.000Z',
    endDate: null,
    icon: 'atom',
    tags: [createTag('tax-ru-off-3', 'Профессиональные праздники', 'holidays.russia.science', 'zap')],
    hashtags: [createHashtag('ht-ru-off-5', 'ДеньНауки'), createHashtag('ht-ru-off-6', 'РАН')],
    createdAt: '2026-02-08T00:00:00.000Z',
    updatedAt: '2026-02-08T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-4',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'Международный женский день',
    description: `### 8 Марта
Всенародный государственный нерабочий праздничный день. Чествование женщин, весны, материнства и красоты.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-03-08T08:00:00.000Z',
    endDate: null,
    icon: 'heart',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-7', '8Марта'), createHashtag('ht-ru-off-8', 'ЖенскийДень')],
    createdAt: '2026-03-08T00:00:00.000Z',
    updatedAt: '2026-03-08T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-5',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День космонавтики',
    description: `### 12 Апреля
Памятная дата России в честь первого в мире полета человека в космическое пространство, совершенного Юрием Алексеевичем Гагариным на корабле «Восток-1» в 1961 году. «Поехали!»`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-04-12T09:07:00.000Z',
    endDate: null,
    icon: 'rocket',
    tags: [createTag('tax-ru-off-2', 'Памятные даты', 'holidays.russia.memorial', 'rocket')],
    hashtags: [createHashtag('ht-ru-off-9', 'ДеньКосмонавтики'), createHashtag('ht-ru-off-10', 'Гагарин')],
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: '2026-04-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://roscosmos.ru',
  },
  {
    id: 'ru-off-6',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'Праздник Весны и Труда',
    description: `### 1 Мая — Первомай
Государственный нерабочий праздничный день. Традиционные весенние шествия, открытие городских парков и фонтанов.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-01T10:00:00.000Z',
    endDate: null,
    icon: 'sun',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-11', '1Мая'), createHashtag('ht-ru-off-12', 'МирТрудМай')],
    createdAt: '2026-05-01T00:00:00.000Z',
    updatedAt: '2026-05-01T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-7',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День России',
    description: `### 12 Июня — Главный государственный праздник
День принятия Декларации о государственном суверенитете Российской Федерации. Торжественное вручение Государственных премий РФ в Кремле, концерты на Красной площади и праздничный салют.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-06-12T10:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-13', 'ДеньРоссии'), createHashtag('ht-ru-off-14', 'МояРоссия')],
    createdAt: '2026-06-12T00:00:00.000Z',
    updatedAt: '2026-06-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://kremlin.ru',
  },
  {
    id: 'ru-off-8',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День Государственного флага Российской Федерации',
    description: `### 22 Августа
Праздник в честь государственного триколора. В городах проходят масштабные автопробеги, флешмобы с развертыванием гигантских флагов и молодежные патриотические акции.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-08-22T09:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-ru-off-2', 'Памятные даты', 'holidays.russia.memorial', 'flag')],
    hashtags: [createHashtag('ht-ru-off-15', 'ФлагРоссии'), createHashtag('ht-ru-off-16', 'Триколор')],
    createdAt: '2026-08-22T00:00:00.000Z',
    updatedAt: '2026-08-22T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-9',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День знаний',
    description: `### 1 Сентября
Государственный праздник. Начало нового учебного года для всех школьников, студентов и педагогов России. Первый звонок и открытые уроки.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-09-01T08:00:00.000Z',
    endDate: null,
    icon: 'book-open',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'book')],
    hashtags: [createHashtag('ht-ru-off-17', 'ДеньЗнаний'), createHashtag('ht-ru-off-18', '1Сентября')],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-10',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День программиста в России',
    description: `### 13 Сентября (256-й день года)
Официальный профессиональный праздник в РФ (Указ Президента РФ № 1034). Отмечается в 256-й день года (2⁸).`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-09-13T09:00:00.000Z',
    endDate: null,
    icon: 'code',
    tags: [createTag('tax-ru-off-3', 'Профессиональные праздники', 'holidays.russia.it', 'code')],
    hashtags: [createHashtag('ht-ru-off-19', 'ДеньПрограммиста'), createHashtag('ht-ru-off-20', 'ITRussia')],
    createdAt: '2026-09-13T00:00:00.000Z',
    updatedAt: '2026-09-13T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-11',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День народного единства',
    description: `### 4 Ноября
Государственный нерабочий праздничный день в память об освобождении Москвы народным ополчением под предводительством Кузьмы Минина и Дмитрия Пожарского в 1612 году.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-04T10:00:00.000Z',
    endDate: null,
    icon: 'users',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-21', 'ДеньНародногоЕдинства'), createHashtag('ht-ru-off-22', 'МыЕдины')],
    createdAt: '2026-11-04T00:00:00.000Z',
    updatedAt: '2026-11-04T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-12',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День матери в России',
    description: `### 29 Ноября 2026 (Последнее воскресенье ноября)
Всероссийский праздник любви, глубокого уважения и признательности матерям. Символ праздника — цветок незабудки.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-29T09:00:00.000Z',
    endDate: null,
    icon: 'heart',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'heart')],
    hashtags: [createHashtag('ht-ru-off-23', 'ДеньМатери'), createHashtag('ht-ru-off-24', 'СпасибоМама')],
    createdAt: '2026-11-29T00:00:00.000Z',
    updatedAt: '2026-11-29T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-13',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День Конституции Российской Федерации',
    description: `### 12 Декабря
Памятная дата России в честь принятия Конституции РФ на всенародном голосовании 12 декабря 1993 года. Основа государственного строя и правопорядка.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-12-12T09:00:00.000Z',
    endDate: null,
    icon: 'landmark',
    tags: [createTag('tax-ru-off-2', 'Памятные даты', 'holidays.russia.memorial', 'landmark')],
    hashtags: [createHashtag('ht-ru-off-25', 'ДеньКонституции'), createHashtag('ht-ru-off-26', 'КонституцияРФ')],
    createdAt: '2026-12-12T00:00:00.000Z',
    updatedAt: '2026-12-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://kremlin.ru',
  },
];

// --- 2. RUSSIAN MILITARY GLORY & ARMED FORCES DAYS (32-FZ) ---
export const RUSSIAN_MILITARY_NOTES: Note[] = [
  {
    id: 'ru-mil-1',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День защитника Отечества',
    description: `### 23 Февраля — День воинской славы России (32-ФЗ)
Всенародный праздник чествования защитников Отечества, ветеранов и действующих военнослужащих армии и флота. Торжественные возложения венков к Могиле Неизвестного Солдата и праздничные салюты.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-23T09:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-1', '23Февраля'), createHashtag('ht-ru-mil-2', 'ДеньЗащитникаОтечества')],
    createdAt: '2026-02-23T00:00:00.000Z',
    updatedAt: '2026-02-23T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://mil.ru',
  },
  {
    id: 'ru-mil-2',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День войск национальной гвардии РФ (Росгвардия)',
    description: `### 27 Марта — День Росгвардии
Профессиональный праздник войск национальной гвардии РФ. Обеспечение общественной безопасности, охрана важных государственных объектов и борьба с терроризмом. «Всегда на страже!»`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-03-27T08:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-3', 'Росгвардия'), createHashtag('ht-ru-mil-4', 'ВВМВД')],
    createdAt: '2026-03-27T00:00:00.000Z',
    updatedAt: '2026-03-27T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://rosguard.gov.ru',
  },
  {
    id: 'ru-mil-3',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День создания Вооруженных Сил Российской Федерации',
    description: `### 7 Мая 1992 года — Основание Вооруженных Сил РФ
Памятный день создания современных ВС РФ на основании Распоряжения Президента Российской Федерации № 219-рп.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-07T09:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-5', 'ВооруженныеСилыРФ'), createHashtag('ht-ru-mil-6', 'АрмияРоссии')],
    createdAt: '2026-05-07T00:00:00.000Z',
    updatedAt: '2026-05-07T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://mil.ru',
  },
  {
    id: 'ru-mil-4',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: '81-я Годовщина Победы в Великой Отечественной войне',
    description: `### 9 Мая — День Победы (32-ФЗ)
Священный всенародный праздник и главный День воинской славы России.
Парад Победы на Красной площади в Москве, шествие «Бессмертного полка», всероссийская минута молчания и грандиозный артиллерийский салют во всех городах-героях.

- **10:00 МСК:** Военный парад на Красной площади
- **19:00 МСК:** Всероссийская минута молчания
- **22:00 МСК:** Праздничный салют Победы`,
    type: 'EVENT' as NoteType,
    startDate: '2026-05-09T07:00:00.000Z',
    endDate: '2026-05-09T22:00:00.000Z',
    icon: 'award',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'star')],
    hashtags: [createHashtag('ht-ru-mil-7', 'ДеньПобеды'), createHashtag('ht-ru-mil-8', '9Мая'), createHashtag('ht-ru-mil-9', 'БессмертныйПолк')],
    createdAt: '2026-05-09T00:00:00.000Z',
    updatedAt: '2026-05-09T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://may9.ru',
  },
  {
    id: 'ru-mil-5',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День пограничника',
    description: `### 28 Мая — День часовых рубежей Родины
Профессиональный праздник сотрудников Пограничной службы ФСБ России. «Граница на замке, а ключ в кармане!» Чествование героев погранвойск.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-28T09:00:00.000Z',
    endDate: null,
    icon: 'shield-alert',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-10', 'ДеньПограничника'), createHashtag('ht-ru-mil-11', 'Погранвойска')],
    createdAt: '2026-05-28T00:00:00.000Z',
    updatedAt: '2026-05-28T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://fsb.ru',
  },
  {
    id: 'ru-mil-6',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День Воздушно-десантных войск (День ВДВ)',
    description: `### 2 Августа — День «Крылатой пехоты»
Праздник гвардейцев-десантников Вооруженных Сил России. «Никто, кроме нас!» Показательные выступления, прыжки с парашютом и встречи ветеранов десанта.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-08-02T09:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-12', 'ДеньВДВ'), createHashtag('ht-ru-mil-13', 'НиктоКромеНас')],
    createdAt: '2026-08-02T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://mil.ru',
  },
  {
    id: 'ru-mil-7',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День Военно-воздушных сил России (День ВВС)',
    description: `### 12 Августа — День ВВС
Памятный день Военно-воздушных сил в составе Воздушно-космических сил РФ. Мастерство пилотажных групп «Русские витязи» и «Стрижи».`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-08-12T09:00:00.000Z',
    endDate: null,
    icon: 'plane',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'plane')],
    hashtags: [createHashtag('ht-ru-mil-14', 'ДеньВВС'), createHashtag('ht-ru-mil-15', 'ВКС')],
    createdAt: '2026-08-12T00:00:00.000Z',
    updatedAt: '2026-08-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-8',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День Бородинского сражения (1812 год)',
    description: `### 8 Сентября — День воинской славы России
Генеральное сражение Отечественной войны 1812 года между русской армией под командованием М.И. Голенищева-Кутузова и французской армией Наполеона Бонапарта.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-09-08T09:00:00.000Z',
    endDate: null,
    icon: 'landmark',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'star')],
    hashtags: [createHashtag('ht-ru-mil-16', 'Бородино'), createHashtag('ht-ru-mil-17', '1812год')],
    createdAt: '2026-09-08T00:00:00.000Z',
    updatedAt: '2026-09-08T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-9',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День победы в Куликовской битве (1380 год)',
    description: `### 21 Сентября — День воинской славы России
Разгром монголо-татарских войск объединенными русскими полками под предводительством великого князя Дмитрия Донского на Куликовом поле.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-09-21T09:00:00.000Z',
    endDate: null,
    icon: 'swords',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'star')],
    hashtags: [createHashtag('ht-ru-mil-18', 'КуликовскаяБитва'), createHashtag('ht-ru-mil-19', 'ДмитрийДонской')],
    createdAt: '2026-09-21T00:00:00.000Z',
    updatedAt: '2026-09-21T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-10',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День подразделений специального назначения (День спецназа)',
    description: `### 24 Октября — Памятный день ВС РФ
День подразделений армейского спецназа в память о директиве Военного министра СССР маршала А.М. Василевского 1950 года о создании рот специального назначения ГРУ.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-10-24T09:00:00.000Z',
    endDate: null,
    icon: 'crosshair',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'crosshair')],
    hashtags: [createHashtag('ht-ru-mil-20', 'ДеньСпецназа'), createHashtag('ht-ru-mil-21', 'СпН')],
    createdAt: '2026-10-24T00:00:00.000Z',
    updatedAt: '2026-10-24T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-11',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День военного разведчика (ГРУ)',
    description: `### 5 Ноября — День военной разведки
Праздник органов военной разведки Главного управления Генерального штаба ВС РФ (ГРУ). «Величие Родины — в твоих славных делах!»`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-05T09:00:00.000Z',
    endDate: null,
    icon: 'eye',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'eye')],
    hashtags: [createHashtag('ht-ru-mil-22', 'ВоеннаяРазведка'), createHashtag('ht-ru-mil-23', 'ГРУ')],
    createdAt: '2026-11-05T00:00:00.000Z',
    updatedAt: '2026-11-05T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-12',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День военного парада на Красной площади (1941 год)',
    description: `### 7 Ноября — День воинской славы России
В память о легендарном историческом военном параде 7 ноября 1941 года, прямо с которого бойцы уходили на фронт защищать Москву.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-07T09:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'star')],
    hashtags: [createHashtag('ht-ru-mil-24', 'Парад1941'), createHashtag('ht-ru-mil-25', 'БитваЗаМоскву')],
    createdAt: '2026-11-07T00:00:00.000Z',
    updatedAt: '2026-11-07T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-13',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День Ракетных войск стратегического назначения (РВСН)',
    description: `### 17 Декабря — День РВСН
Памятный день стратегических ракетчиков Вооруженных Сил России. Главный ядерный щит и гарант суверенитета Отечества. «После нас — тишина!»`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-12-17T09:00:00.000Z',
    endDate: null,
    icon: 'zap',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'zap')],
    hashtags: [createHashtag('ht-ru-mil-26', 'РВСН'), createHashtag('ht-ru-mil-27', 'ЯдерныйЩит')],
    createdAt: '2026-12-17T00:00:00.000Z',
    updatedAt: '2026-12-17T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];