import { PublicFeedPreset } from '@lenta/shared';

export const PUBLIC_FEED_PRESETS: PublicFeedPreset[] = [
  {
    id: 'preset-orthodox-holidays',
    title: 'Православный календарь',
    slug: 'orthodox-holidays',
    icon: '☦️',
    category: 'Православие',
    description: 'Пасха Христова (12 апреля 2026 г.), двунадесятые и великие праздники, многодневные посты и дни памяти святых.',
    color: '#f59e0b',
    count: 24,
  },
  {
    id: 'preset-catholic-holidays',
    title: 'Католический календарь',
    slug: 'catholic-holidays',
    icon: '✝️',
    category: 'Католицизм',
    description: 'Литургический год латинского обряда: Пасха (5 апреля 2026 г.), Пепельная среда, Рождество и главные торжества.',
    color: '#8b5cf6',
    count: 28,
  },
  {
    id: 'preset-islamic-holidays',
    title: 'Исламский календарь',
    slug: 'islamic-holidays',
    icon: '☪️',
    category: 'Ислам (Хиджра)',
    description: 'Священный месяц Рамадан (18 фев – 19 мар), Ночь могущества (Ляйлят аль-Кадр), Ураза-байрам, Курбан-байрам 1447–1448 гг.',
    color: '#10b981',
    count: 10,
  },
  {
    id: 'preset-world-religions',
    title: 'Мировые религии',
    slug: 'world-religions',
    icon: '🕊️',
    category: 'Межконфессиональный',
    description: 'Праздники мировых религий: Ислам (Рамадан, Курбан-байрам), Иудаизм (Песах, Рош ха-Шана, Ханука), Буддизм (Сагаалган, Весак).',
    color: '#06b6d4',
    count: 21,
  },
  {
    id: 'preset-russian-official',
    title: 'Русские государственные праздники',
    slug: 'russian-official',
    icon: '🇷🇺',
    category: 'Праздники РФ',
    description: 'Официальные нерабочие праздничные дни (ТК РФ ст. 112), памятные даты, научные и культурные события 2026 года.',
    color: '#ef4444',
    count: 17,
  },
  {
    id: 'preset-russian-military',
    title: 'Дни воинской славы России',
    slug: 'russian-military',
    icon: '🎖️',
    category: 'Воинская слава РФ',
    description: 'Дни воинской славы России (32-ФЗ), рода войск Вооруженных Сил, исторические сражения и чествование защитников Отечества.',
    color: '#eab308',
    count: 39,
  },
  {
    id: 'preset-world-holidays',
    title: 'Праздники стран мира',
    slug: 'world-holidays',
    icon: '🌍',
    category: 'Праздники стран',
    description: 'Знаменитые праздники стран мира: Китайский Новый год, День взятия Бастилии, День благодарения, Хэллоуин.',
    color: '#3b82f6',
    count: 12,
  },
  {
    id: 'preset-russian-holidays',
    title: 'Все русские праздники (сводный)',
    slug: 'russian-holidays',
    icon: '🇷🇺',
    category: 'Сводный календарь РФ',
    description: 'Полный свод государственных, воинских и профессиональных праздников России в 2026 году.',
    color: '#dc2626',
    count: 56,
  },
  {
    id: 'preset-christian-holidays',
    title: 'Все христианские праздники (сводный)',
    slug: 'christian-holidays',
    icon: '✝️',
    category: 'Христианский мир',
    description: 'Сводный календарь восточной и западной христианских традиций: православные и католические торжества.',
    color: '#d97706',
    count: 52,
  },
  {
    id: 'preset-politics-2026',
    title: 'Политика 2026',
    slug: 'politics-2026',
    icon: '🏛️',
    category: 'Геополитика & Выборы',
    description: 'Ключевые международные саммиты, выборы, парламентские сессии и геополитические соглашения 2026 года.',
    color: '#3b82f6',
    count: 7,
  },
  {
    id: 'preset-wow-calendar',
    title: 'World of Warcraft Календарь',
    slug: 'wow-calendar',
    icon: '⚔️',
    category: 'Игровые события & Рейды',
    description: 'Расписание игровых событий Азерота, открытие рейдов Midnight, Ярмарка Новолуния и сезонные праздники.',
    color: '#a855f7',
    count: 8,
  },
];

// Helper to create valid Tag
export const createTag = (id: string, name: string, path: string, icon = 'bookmark') => ({
  id,
  name,
  path,
  icon,
  updatedAt: '2026-01-01T00:00:00.000Z',
  deletedAt: null,
});

// Helper to create valid Hashtag
export const createHashtag = (id: string, name: string) => ({
  id,
  name,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  deletedAt: null,
});
