import { Note, NoteType } from '@lenta/shared';
import { createTag, createHashtag } from './types';

// --- 7. WORLD COUNTRIES HOLIDAYS ---
export const WORLD_HOLIDAYS_NOTES: Note[] = [
  {
    id: 'w-hol-1',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'Китайский Новый год (Чуньцзе — Праздник Весны)',
    description: `### 17 Февраля 2026 г. — Наступление года Огненной Лошади
Традиционный праздник встречи Нового года по лунному календарю в Китае и странах Восточной Азии. Красные фонари, танец дракона и семейные застолья.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-02-17T00:00:00.000Z',
    endDate: '2026-02-17T23:59:59.000Z',
    icon: 'sparkles',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'globe')],
    hashtags: [createHashtag('ht-w-hol-1', 'КитайскийНовыйГод'), createHashtag('ht-w-hol-2', 'ChunJie')],
    createdAt: '2026-02-17T00:00:00.000Z',
    updatedAt: '2026-02-17T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-2',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'День святого Патрика (St. Patrick\'s Day)',
    description: `### 17 Марта — Национальный праздник Ирландии
Всемирный праздник ирландской культуры. Зеленый цвет, лист трилистника (shamrock), шествия волынщиков и парады от Дублина до Нью-Йорка.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-03-17T10:00:00.000Z',
    endDate: null,
    icon: 'clover',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'globe')],
    hashtags: [createHashtag('ht-w-hol-3', 'ДеньСвятогоПатрика'), createHashtag('ht-w-hol-4', 'StPatricksDay')],
    createdAt: '2026-03-17T00:00:00.000Z',
    updatedAt: '2026-03-17T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-3',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'День независимости США (4th of July)',
    description: `### 4 Июля 1776 года
Государственный праздник в честь принятия Декларации независимости Соединенных Штатов Америки. Традиционные фейерверки, барбекю и патриотические парады.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-07-04T12:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'flag')],
    hashtags: [createHashtag('ht-w-hol-5', '4thOfJuly'), createHashtag('ht-w-hol-6', 'IndependenceDay')],
    createdAt: '2026-07-04T00:00:00.000Z',
    updatedAt: '2026-07-04T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-4',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'Национальный праздник Франции (День взятия Бастилии)',
    description: `### 14 Июля 1789 года
Годовщина взятия крепости Бастилия. Грандиозный военный парад на Елисейских полях в Париже в присутствии Президента Франции и огни Эйфелевой башни.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-07-14T10:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'flag')],
    hashtags: [createHashtag('ht-w-hol-7', 'ДеньБастилии'), createHashtag('ht-w-hol-8', 'BastilleDay')],
    createdAt: '2026-07-14T00:00:00.000Z',
    updatedAt: '2026-07-14T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-5',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'Хэллоуин (Канун Дня всех святых)',
    description: `### 31 Октября
Праздник костюмов, тыквенных фонариков Джека (Jack-o'-lantern) и традиции «Trick or Treat» («Сладость или гадость»), популярный во всем мире.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-10-31T18:00:00.000Z',
    endDate: '2026-10-31T23:59:59.000Z',
    icon: 'skull',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'skull')],
    hashtags: [createHashtag('ht-w-hol-9', 'Halloween'), createHashtag('ht-w-hol-10', 'Хэллоуин')],
    createdAt: '2026-10-31T00:00:00.000Z',
    updatedAt: '2026-10-31T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-6',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'День благодарения (Thanksgiving Day)',
    description: `### 26 Ноября 2026 г. (Четвертый четверг ноября)
Традиционный американский и канадский праздник выражения благодарности за урожай и блага года. Запеченная индейка, тыквенный пирог и семейный круг.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-26T14:00:00.000Z',
    endDate: null,
    icon: 'heart',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'heart')],
    hashtags: [createHashtag('ht-w-hol-11', 'Thanksgiving'), createHashtag('ht-w-hol-12', 'ДеньБлагодарения')],
    createdAt: '2026-11-26T00:00:00.000Z',
    updatedAt: '2026-11-26T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];
