import { Note, NoteType, PublicFeedPreset } from '@lenta/shared';

export const PUBLIC_FEED_PRESETS: PublicFeedPreset[] = [
  {
    id: 'preset-russian-holidays',
    title: 'Русские праздники',
    slug: 'russian-holidays',
    icon: '🇷🇺',
    category: 'Государственные праздники',
    description: 'Официальные нерабочие праздничные дни, памятные даты и государственные торжества России в 2026 году.',
    color: '#ef4444',
    count: 34,
  },
  {
    id: 'preset-christian-holidays',
    title: 'Христианские праздники',
    slug: 'christian-holidays',
    icon: '✝️',
    category: 'Православный календарь',
    description: 'Двунадесятые и великие православные праздники, Пасха Христова и ключевые дни литургического года 2026.',
    color: '#f59e0b',
    count: 20,
  },
  {
    id: 'preset-politics-2026',
    title: 'Политика 2026',
    slug: 'politics-2026',
    icon: '🏛️',
    category: 'Геополитика & Выборы',
    description: 'Ключевые международные саммиты, выборы, парламентские сессии и геополитические соглашения 2026 года.',
    color: '#3b82f6',
    count: 7,
  },
  {
    id: 'preset-wow-calendar',
    title: 'World of Warcraft Календарь',
    slug: 'wow-calendar',
    icon: '⚔️',
    category: 'Игровые события & Рейды',
    description: 'Расписание игровых событий Азерота, открытие рейдов Midnight, Ярмарка Новолуния и сезонные праздники.',
    color: '#a855f7',
    count: 8,
  },
];

export const PRESET_SAMPLE_NOTES: Record<string, Note[]> = {
  'russian-holidays': [
    {
      id: 'ru-hol-1',
      feedId: 'preset-russian-holidays',
      title: 'Новый 2026 Год и Новогодние каникулы',
      description: `### Празднование Нового Года в России
Официальные новогодние праздничные каникулы продлятся с 1 по 8 января 2026 года.
Главные городские ёлки, световые инсталляции и праздничные площадки открыты во всех регионах страны.

- **Даты отдыха:** 1–8 января 2026 г.
- **Статус:** Официальный государственный нерабочий праздничный день.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-01-01T00:00:00.000Z',
      endDate: '2026-01-08T23:59:59.000Z',
      icon: 'sparkles',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-01-01T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-1', name: 'НовыйГод', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-ru-2', name: 'Праздники2026', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://government.ru',
    },
    {
      id: 'ru-hol-2',
      feedId: 'preset-russian-holidays',
      title: 'День защитника Отечества',
      description: `### 23 Февраля
День воинской славы и всенародный праздник чествования защитников страны, ветеранов и военнослужащих.

> Торжественные возложения цветов к Могиле Неизвестного Солдата у Кремлёвской стены и праздничные артиллерийские салюты.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-02-23T09:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-02-23T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-3', name: '23Февраля', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-02-23T00:00:00.000Z',
      updatedAt: '2026-02-23T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://kremlin.ru',
    },
    {
      id: 'ru-hol-3',
      feedId: 'preset-russian-holidays',
      title: 'Международный женский день',
      description: `### 8 Марта
Весенний праздник чествования женщин, материнства, весны и красоты. Традиционные концерты, выставки и цветочные фестивали.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-03-08T08:00:00.000Z',
      endDate: null,
      icon: 'heart',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-03-08T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-4', name: '8Марта', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-03-08T00:00:00.000Z',
      updatedAt: '2026-03-08T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-mar-27',
      feedId: 'preset-russian-holidays',
      title: 'День войск национальной гвардии РФ (День внутренних войск)',
      description: `### 27 Марта — День войск национальной гвардии РФ (День внутренних войск)
Профессиональный праздник Росгвардии (ранее День внутренних войск МВД России). Охрана порядка, государственных объектов и борьба с терроризмом.

> «Всегда на страже!»`,
      type: 'EVENT' as NoteType,
      startDate: '2026-03-27T08:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-03-27T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-rosgvard', name: 'Росгвардия', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-ru-vv', name: 'ВнутренниеВойска', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-03-27T00:00:00.000Z',
      updatedAt: '2026-03-27T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://rosguard.gov.ru',
    },
    {
      id: 'ru-hol-apr-08',
      feedId: 'preset-russian-holidays',
      title: 'День сотрудников военных комиссариатов',
      description: `### 8 Апреля
Профессиональный праздник сотрудников военных комиссариатов Вооруженных Сил РФ. Обеспечение мобилизационной готовности и призыва.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-04-08T09:00:00.000Z',
      endDate: null,
      icon: 'file-text',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-04-08T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-voenkom', name: 'Военкомат', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-04-08T00:00:00.000Z',
      updatedAt: '2026-04-08T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-4',
      feedId: 'preset-russian-holidays',
      title: 'Праздник Весны и Труда',
      description: `### 1 Мая — Первомай
Традиционный весенний праздник трудящихся, открытия летнего паркового сезона и праздничных шествий.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-05-01T10:00:00.000Z',
      endDate: null,
      icon: 'sun',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-05-01T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-5', name: '1Мая', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-05-01T00:00:00.000Z',
      updatedAt: '2026-05-01T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-5',
      feedId: 'preset-russian-holidays',
      title: '81-я Годовщина Победы в Великой Отечественной войне',
      description: `### 9 Мая — День Победы
Главный священный праздник страны: Парад Победы на Красной площади в Москве, шествие Бессмертного полка, минута молчания и грандиозный салют.

- **10:00 МСК:** Военный парад на Красной площади
- **19:00 МСК:** Всероссийская минута молчания
- **22:00 МСК:** Праздничный салют`,
      type: 'EVENT' as NoteType,
      startDate: '2026-05-09T07:00:00.000Z',
      endDate: '2026-05-09T22:00:00.000Z',
      icon: 'award',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-05-09T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-6', name: 'ДеньПобеды', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-ru-7', name: '9Мая', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-05-09T00:00:00.000Z',
      updatedAt: '2026-05-09T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://may9.ru',
    },
    {
      id: 'ru-hol-may-07',
      feedId: 'preset-russian-holidays',
      title: 'День создания Вооруженных Сил Российской Федерации',
      description: `### 7 Мая 1992 года — День создания Вооруженных Сил РФ
Памятный день основания современных Вооруженных Сил России по Распоряжению Президента РФ № 219-рп.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-05-07T09:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-05-07T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-vsrf', name: 'ВооруженныеСилы', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-05-07T00:00:00.000Z',
      updatedAt: '2026-05-07T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://mil.ru',
    },
    {
      id: 'ru-hol-may-28',
      feedId: 'preset-russian-holidays',
      title: 'День пограничника',
      description: `### 28 Мая — День пограничника
Всенародный праздник часовых рубежей Родины — Пограничной службы ФСБ России. «Граница на замке!»`,
      type: 'EVENT' as NoteType,
      startDate: '2026-05-28T09:00:00.000Z',
      endDate: null,
      icon: 'shield-check',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-05-28T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-pogran', name: 'ДеньПограничника', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-05-28T00:00:00.000Z',
      updatedAt: '2026-05-28T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://fsb.ru',
    },
    {
      id: 'ru-hol-6',
      feedId: 'preset-russian-holidays',
      title: 'День России',
      description: `### 12 Июня — День России
Государственный праздник Российской Федерации, вручение Государственных премий в Кремле, торжественные концерты и фестивали на центральных площадях.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-06-12T10:00:00.000Z',
      endDate: null,
      icon: 'flag',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-06-12T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-8', name: 'ДеньРоссии', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-06-12T00:00:00.000Z',
      updatedAt: '2026-06-12T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-7',
      feedId: 'preset-russian-holidays',
      title: 'День Государственного флага Российской Федерации',
      description: `### 22 Августа
Праздник в честь государственного триколора. В городах проходят масштабные автопробеги, флешмобы с развертыванием гигантских флагов и молодежные патриотические акции.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-08-22T09:00:00.000Z',
      endDate: null,
      icon: 'flag',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-08-22T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-9', name: 'ФлагРоссии', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-08-22T00:00:00.000Z',
      updatedAt: '2026-08-22T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-sep-1',
      feedId: 'preset-russian-holidays',
      title: 'День знаний',
      description: `### 1 Сентября
Государственный праздник. Начало нового учебного года для всех школьников, студентов и педагогов России. Торжественные линейки и первый звонок.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-01T08:00:00.000Z',
      endDate: null,
      icon: 'book-open',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-09-01T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-sep-1', name: 'ДеньЗнаний', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-01T00:00:00.000Z',
      updatedAt: '2026-09-01T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-sep-2',
      feedId: 'preset-russian-holidays',
      title: 'День окончания ВМВ и День солидарности в борьбе с терроризмом',
      description: `### 3 Сентября (32-ФЗ)
- **Победа над милитаристской Японией и окончание Второй мировой войны (1945 г.):** День воинской славы России.
- **День солидарности в борьбе с терроризмом:** Памятная дата в честь жертв Беслана.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-03T09:00:00.000Z',
      endDate: null,
      icon: 'shield-alert',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-09-03T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-sep-2', name: '3Сентября', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-03T00:00:00.000Z',
      updatedAt: '2026-09-03T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-sep-3',
      feedId: 'preset-russian-holidays',
      title: 'День Бородинского сражения (1812 год)',
      description: `### 8 Сентября
День воинской славы России. Крупнейшее генеральное сражение Отечественной войны 1812 года под командованием М.И. Голенищева-Кутузова.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-08T09:00:00.000Z',
      endDate: null,
      icon: 'landmark',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-09-08T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-sep-3', name: 'Бородино', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-08T00:00:00.000Z',
      updatedAt: '2026-09-08T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-sep-4',
      feedId: 'preset-russian-holidays',
      title: 'День программиста в России',
      description: `### 13 Сентября (256-й день года)
Официальный профессиональный праздник в РФ (Указ Президента РФ № 1034). Отмечается в 256-й день года (2⁸).`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-13T09:00:00.000Z',
      endDate: null,
      icon: 'code',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-09-13T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-sep-4', name: 'ДеньПрограммиста', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-13T00:00:00.000Z',
      updatedAt: '2026-09-13T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-sep-5',
      feedId: 'preset-russian-holidays',
      title: 'Единый день голосования 2026 (Выборы в Госдуму IX созыва)',
      description: `### 18–20 Сентября 2026
3-дневное общероссийское голосование на выборах депутатов Государственной Думы РФ IX созыва и региональных выборах.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-09-18T00:00:00.000Z',
      endDate: '2026-09-20T20:00:00.000Z',
      icon: 'vote',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-09-18T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-sep-5', name: 'Выборы2026', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-18T00:00:00.000Z',
      updatedAt: '2026-09-18T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://cikrf.ru',
    },
    {
      id: 'ru-hol-sep-6',
      feedId: 'preset-russian-holidays',
      title: 'День победы в Куликовской битве (1380 год)',
      description: `### 21 Сентября
День воинской славы России. Разгром ордынских войск объединенными русскими полками великого князя Дмитрия Донского на Куликовом поле.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-21T09:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-09-21T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-sep-6', name: 'КуликовскаяБитва', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-21T00:00:00.000Z',
      updatedAt: '2026-09-21T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-sep-7',
      feedId: 'preset-russian-holidays',
      title: 'День воспитателя и всех дошкольных работников',
      description: `### 27 Сентября
Общероссийский профессиональный праздник в честь всех работников дошкольных образовательных учреждений.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-27T09:00:00.000Z',
      endDate: null,
      icon: 'heart',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-09-27T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-sep-7', name: 'ДеньВоспитателя', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-27T00:00:00.000Z',
      updatedAt: '2026-09-27T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-8',
      feedId: 'preset-russian-holidays',
      title: 'День народного единства',
      description: `### 4 Ноября
Государственный праздник в память об освобождении Москвы народным ополчением под предводительством Кузьмы Минина и Дмитрия Пожарского в 1612 году.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-11-04T10:00:00.000Z',
      endDate: null,
      icon: 'users',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-11-04T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-10', name: 'ДеньНародногоЕдинства', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-04T00:00:00.000Z',
      updatedAt: '2026-11-04T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-nov-1',
      feedId: 'preset-russian-holidays',
      title: 'День военного парада на Красной площади (1941 год)',
      description: `### 7 Ноября (32-ФЗ)
День воинской славы России. Легендарный военный парад на Красной площади в Москве в 1941 году, откуда бойцы уходили прямо на фронт защищать столицу.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-11-07T09:00:00.000Z',
      endDate: null,
      icon: 'flag',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-11-07T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-nov-1', name: '7Ноября', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-07T00:00:00.000Z',
      updatedAt: '2026-11-07T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-nov-2',
      feedId: 'preset-russian-holidays',
      title: 'День сотрудника органов внутренних дел (День полиции)',
      description: `### 10 Ноября
Официальный профессиональный праздник сотрудников МВД России. Чествование защитников правопорядка и безопасности граждан.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-11-10T09:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-11-10T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-nov-2', name: 'ДеньПолиции', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-10T00:00:00.000Z',
      updatedAt: '2026-11-10T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-nov-3',
      feedId: 'preset-russian-holidays',
      title: 'День ракетных войск и артиллерии',
      description: `### 19 Ноября
Памятный день ВС РФ в честь артподготовки контрнаступления под Сталинградом 19 ноября 1942 года. «Артиллерия — бог войны!»`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-11-19T09:00:00.000Z',
      endDate: null,
      icon: 'crosshair',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-11-19T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-nov-3', name: 'ДеньАртиллерии', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-19T00:00:00.000Z',
      updatedAt: '2026-11-19T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-nov-4',
      feedId: 'preset-russian-holidays',
      title: 'День морской пехоты России',
      description: `### 27 Ноября
Праздник «черных беретов» ВМФ России в память указа Петра I 1705 года о создании полка морских солдат. «Где мы — там победа!»`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-11-27T09:00:00.000Z',
      endDate: null,
      icon: 'anchor',
      tags: [{ id: 'tax-ru-2', name: 'Памятные даты', path: 'holidays.memorial', icon: 'star', updatedAt: '2026-11-27T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-nov-4', name: 'МорскаяПехота', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-27T00:00:00.000Z',
      updatedAt: '2026-11-27T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-nov-5',
      feedId: 'preset-russian-holidays',
      title: 'День матери в России',
      description: `### 29 Ноября 2026 (Последнее воскресенье ноября)
Всероссийский праздник выражения глубокой любви, уважения и благодарности матерям. Символ праздника — цветок незабудки.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-11-29T09:00:00.000Z',
      endDate: null,
      icon: 'heart',
      tags: [{ id: 'tax-ru-1', name: 'Государственные праздники', path: 'holidays.russia', icon: 'flag', updatedAt: '2026-11-29T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-nov-5', name: 'ДеньМатери', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-29T00:00:00.000Z',
      updatedAt: '2026-11-29T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-aug-12',
      feedId: 'preset-russian-holidays',
      title: 'День Военно-воздушных сил России (День ВВС)',
      description: `### 12 Августа — День ВВС
Памятный день Военно-воздушных сил в составе ВКС РФ. Показательные полеты групп «Русские витязи» и «Стрижи».`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-08-12T09:00:00.000Z',
      endDate: null,
      icon: 'plane',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-08-12T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-vvs', name: 'ДеньВВС', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-08-12T00:00:00.000Z',
      updatedAt: '2026-08-12T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-sep-tank',
      feedId: 'preset-russian-holidays',
      title: 'День танкиста',
      description: `### 13 Сентября 2026 (Второе воскресенье сентября) — День танкиста
Профессиональный праздник танкистов и танкостроителей. «Броня крепка, и танки наши быстры!»`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-13T09:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-09-13T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-tank', name: 'ДеньТанкиста', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-13T00:00:00.000Z',
      updatedAt: '2026-09-13T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-oct-01',
      feedId: 'preset-russian-holidays',
      title: 'День Сухопутных войск России',
      description: `### 1 Октября — День Сухопутных войск РФ
Памятный день ВС РФ в честь Приговора Ивана Грозного 1550 года об «избранной тысяче» — рождении регулярной пехоты.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-10-01T09:00:00.000Z',
      endDate: null,
      icon: 'swords',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-10-01T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-sv', name: 'СухопутныеВойска', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-10-01T00:00:00.000Z',
      updatedAt: '2026-10-01T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-oct-04',
      feedId: 'preset-russian-holidays',
      title: 'День Космических войск России',
      description: `### 4 Октября — День Космических войск
В честь запуска первого искусственного спутника Земли 4 октября 1957 года. СПРН, контроль космоса и орбитальные группировки.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-10-04T09:00:00.000Z',
      endDate: null,
      icon: 'rocket',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-10-04T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-space', name: 'КосмическиеВойска', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-10-04T00:00:00.000Z',
      updatedAt: '2026-10-04T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-oct-24',
      feedId: 'preset-russian-holidays',
      title: 'День подразделений специального назначения (День спецназа)',
      description: `### 24 Октября — День спецназа
Памятный день подразделений специального назначения Вооруженных Сил РФ в память директивы 1950 года о создании рот СпН.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-10-24T09:00:00.000Z',
      endDate: null,
      icon: 'crosshair',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-10-24T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-spn', name: 'ДеньСпецназа', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-10-24T00:00:00.000Z',
      updatedAt: '2026-10-24T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-nov-05',
      feedId: 'preset-russian-holidays',
      title: 'День военного разведчика',
      description: `### 5 Ноября — День военного разведчика
Праздник органов военной разведки (ГРУ). «Величие Родины — в твоих славных делах!»`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-11-05T09:00:00.000Z',
      endDate: null,
      icon: 'eye',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-11-05T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-gru', name: 'ВоеннаяРазведка', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-05T00:00:00.000Z',
      updatedAt: '2026-11-05T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-dec-09',
      feedId: 'preset-russian-holidays',
      title: 'День Героев Отечества',
      description: `### 9 Декабря — День Героев Отечества (32-ФЗ)
Чествование Героев Советского Союза, Героев Российской Федерации и кавалеров орденов Славы и Святого Георгия.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-12-09T09:00:00.000Z',
      endDate: null,
      icon: 'award',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-12-09T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-heroes', name: 'ДеньГероевОтечества', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-12-09T00:00:00.000Z',
      updatedAt: '2026-12-09T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-dec-17',
      feedId: 'preset-russian-holidays',
      title: 'День Ракетных войск стратегического назначения (РВСН)',
      description: `### 17 Декабря — День РВСН
Памятный день стратегических ракетчиков РФ. Главный ядерный щит Отечества. «После нас — тишина».`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-12-17T09:00:00.000Z',
      endDate: null,
      icon: 'zap',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-12-17T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-rvsn', name: 'РВСН', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-12-17T00:00:00.000Z',
      updatedAt: '2026-12-17T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'ru-hol-dec-20',
      feedId: 'preset-russian-holidays',
      title: 'День работника органов безопасности РФ',
      description: `### 20 Декабря — День органов безопасности РФ
Профессиональный праздник сотрудников ФСБ, СВР, ФСО и ГУСП. Защита суверенитета и государственная безопасность.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-12-20T09:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-ru-2', name: 'Военные праздники', path: 'holidays.russia.military', icon: 'shield', updatedAt: '2026-12-20T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-ru-fsb', name: 'ДеньФСБ', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-12-20T00:00:00.000Z',
      updatedAt: '2026-12-20T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
  ],

  'christian-holidays': [
    {
      id: 'chr-hol-1',
      feedId: 'preset-christian-holidays',
      title: 'Рождество Христово',
      description: `### Праздник Рождества Господа Бога и Спаса нашего Иисуса Христа
Один из главных двунадесятых праздников Православной Церкви. Торжественные ночные богослужения во всех соборах и храмах.`,
      type: 'EVENT' as NoteType,
      startDate: '2026-01-07T00:00:00.000Z',
      endDate: '2026-01-07T23:59:59.000Z',
      icon: 'star',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-01-07T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-1', name: 'Рождество', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-01-07T00:00:00.000Z',
      updatedAt: '2026-01-07T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://patriarchia.ru',
    },
    {
      id: 'chr-hol-2',
      feedId: 'preset-christian-holidays',
      title: 'Святое Богоявление (Крещение Господне)',
      description: `### Крещение Господа Бога и Спаса нашего Иисуса Христа
Великое освящение воды (Великая агиасма), традиционные крещенские купания в освященных иорданях.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-01-19T06:00:00.000Z',
      endDate: null,
      icon: 'droplet',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-01-19T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-2', name: 'Крещение', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-01-19T00:00:00.000Z',
      updatedAt: '2026-01-19T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-3',
      feedId: 'preset-christian-holidays',
      title: 'Сретение Господне',
      description: `### Сретение Господа нашего Иисуса Христа
Встреча Ветхого и Нового Заветов, встреча старца Симеона и пророчицы Анны с Богомладенцем Иисусом. Также отмечается как День православной молодежи.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-02-15T08:00:00.000Z',
      endDate: null,
      icon: 'sparkles',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-02-15T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-3', name: 'Сретение', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-02-15T00:00:00.000Z',
      updatedAt: '2026-02-15T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-4',
      feedId: 'preset-christian-holidays',
      title: 'Благовещение Пресвятой Богородицы',
      description: `### Благовещение Пресвятой Владычицы нашей Богородицы
Возвещение архангелом Гавриилом Деве Марии благой вести о грядущем рождении Иисуса Христа. Традиция выпускать на волю белых голубей.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-04-07T08:00:00.000Z',
      endDate: null,
      icon: 'sun',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-04-07T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-4', name: 'Благовещение', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-04-07T00:00:00.000Z',
      updatedAt: '2026-04-07T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-5',
      feedId: 'preset-christian-holidays',
      title: 'Вход Господень в Иерусалим (Вербное воскресенье)',
      description: `### Неделя 6-я Великого поста
Торжественный вход Спасителя в Иерусалим перед крестными страданиями. Освящение веточек вербы в храмах.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-04-05T08:00:00.000Z',
      endDate: null,
      icon: 'feather',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-04-05T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-5', name: 'ВербноеВоскресенье', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-04-05T00:00:00.000Z',
      updatedAt: '2026-04-05T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-6',
      feedId: 'preset-christian-holidays',
      title: 'Светлое Христово Воскресение — ПАСХА',
      description: `### Праздников Праздник и Торжество из Торжеств
Главное событие церковного года в память о Воскресении Господа Иисуса Христа. Доставка Благодатного Огня из Иерусалима, крестные ходы, освящение куличей и крашеных яиц.

> **Христос Воскресе! — Воистину Воскресе!**`,
      type: 'EVENT' as NoteType,
      startDate: '2026-04-12T00:00:00.000Z',
      endDate: '2026-04-12T23:59:59.000Z',
      icon: 'sparkles',
      tags: [{ id: 'tax-chr-2', name: 'Пасхальный цикл', path: 'church.easter', icon: 'sun', updatedAt: '2026-04-12T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-6', name: 'Пасха2026', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-chr-7', name: 'ХристосВоскресе', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-04-12T00:00:00.000Z',
      updatedAt: '2026-04-12T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://patriarchia.ru',
    },
    {
      id: 'chr-hol-7',
      feedId: 'preset-christian-holidays',
      title: 'Вознесение Господне',
      description: `### 40-й день по Пасхе
Вознесение Господа Иисуса Христа во плоти на небеса в присутствии Пресвятой Богородицы и апостолов на горе Елеон.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-05-21T08:00:00.000Z',
      endDate: null,
      icon: 'cloud-lightning',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-05-21T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-8', name: 'Вознесение', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-05-21T00:00:00.000Z',
      updatedAt: '2026-05-21T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-8',
      feedId: 'preset-christian-holidays',
      title: 'День Святой Троицы (Пятидесятница)',
      description: `### 50-й день по Пасхе
Сошествие Святого Духа на апостолов и день рождения Церкви Христовой. Храмы украшаются свежей зеленью берез и полевыми цветами.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-05-31T08:00:00.000Z',
      endDate: null,
      icon: 'feather',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-05-31T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-9', name: 'Троица', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-05-31T00:00:00.000Z',
      updatedAt: '2026-05-31T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-9',
      feedId: 'preset-christian-holidays',
      title: 'Успение Пресвятой Богородицы',
      description: `### Окончание Успенского поста
Переход Божией Матери в вечную жизнь и взятие Ее тела и души на Небо. Чин погребения Плащаницы Богородицы.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-08-28T08:00:00.000Z',
      endDate: null,
      icon: 'bookmark',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-08-28T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-10', name: 'Успение', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-08-28T00:00:00.000Z',
      updatedAt: '2026-08-28T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-sep-1',
      feedId: 'preset-christian-holidays',
      title: 'Усекновение главы Иоанна Предтечи',
      description: `### Великий праздник и день строгого поста
Мученическая кончина святого пророка, Предтечи и Крестителя Господня Иоанна. День памяти воинов, за веру и Отечество на поле бранном убиенных.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-11T08:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-chr-3', name: 'Великие праздники', path: 'church.feasts', icon: 'shield', updatedAt: '2026-09-11T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-sep-1', name: 'ИоаннПредтеча', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-11T00:00:00.000Z',
      updatedAt: '2026-09-11T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-sep-2',
      feedId: 'preset-christian-holidays',
      title: 'День памяти святого князя Александра Невского',
      description: `### Перенесение мощей благоверного великого князя
День памяти защитника Руси и православной веры. Перенесение мощей из Владимира в Санкт-Петербург в 1724 году Императором Петром I.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-12T08:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-chr-3', name: 'Великие праздники', path: 'church.feasts', icon: 'shield', updatedAt: '2026-09-12T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-sep-2', name: 'АлександрНевский', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-12T00:00:00.000Z',
      updatedAt: '2026-09-12T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-sep-3',
      feedId: 'preset-christian-holidays',
      title: 'Церковное новолетие (Начало индикта)',
      description: `### Начало нового церковного года
Первый день богослужебного церковного года в православной традиции (1 сентября по ст. ст.). День духовного обновления.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-14T08:00:00.000Z',
      endDate: null,
      icon: 'sparkles',
      tags: [{ id: 'tax-chr-3', name: 'Великие праздники', path: 'church.feasts', icon: 'shield', updatedAt: '2026-09-14T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-sep-3', name: 'Новолетие', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-14T00:00:00.000Z',
      updatedAt: '2026-09-14T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-sep-4',
      feedId: 'preset-christian-holidays',
      title: 'Рождество Пресвятой Богородицы',
      description: `### Первый двунадесятый праздник церковного года
Воспоминание рождения Девы Марии у праведных Иоакима и Анны. Начало спасения человеческого рода.`,
      type: 'EVENT' as NoteType,
      startDate: '2026-09-21T00:00:00.000Z',
      endDate: '2026-09-21T23:59:59.000Z',
      icon: 'star',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-09-21T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-sep-4', name: 'РождествоБогородицы', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-21T00:00:00.000Z',
      updatedAt: '2026-09-21T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://patriarchia.ru',
    },
    {
      id: 'chr-hol-sep-5',
      feedId: 'preset-christian-holidays',
      title: 'Воздвижение Креста Господня',
      description: `### Двунадесятый праздник и день строгого поста
Обретение Честного Креста Спасителя царицей Еленой в Иерусалиме в 326 году. Торжественное вынесение и воздвижение Креста в храмах.`,
      type: 'EVENT' as NoteType,
      startDate: '2026-09-27T00:00:00.000Z',
      endDate: '2026-09-27T23:59:59.000Z',
      icon: 'bookmark',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-09-27T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-sep-5', name: 'ВоздвижениеКреста', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-27T00:00:00.000Z',
      updatedAt: '2026-09-27T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-sep-6',
      feedId: 'preset-christian-holidays',
      title: 'День памяти святых мучениц Веры, Надежды, Любови и матери их Софии',
      description: `### Память святых мучениц
Подвиг святых сестер и их матери в Риме II века. Празднование главных христианских добродетелей — Веры, Надежды и Любви.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-09-30T08:00:00.000Z',
      endDate: null,
      icon: 'heart',
      tags: [{ id: 'tax-chr-3', name: 'Великие праздники', path: 'church.feasts', icon: 'shield', updatedAt: '2026-09-30T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-sep-6', name: 'ВераНадеждаЛюбовь', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-30T00:00:00.000Z',
      updatedAt: '2026-09-30T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-10',
      feedId: 'preset-christian-holidays',
      title: 'Покров Пресвятой Богородицы',
      description: `### Великий праздник
Явление Богоматери святому Андрею Юродивому во Влахернском храме Константинополя, распростершей Свой омофор над молящимися.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-10-14T08:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-chr-3', name: 'Великие праздники', path: 'church.feasts', icon: 'shield', updatedAt: '2026-10-14T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-11', name: 'Покров', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-10-14T00:00:00.000Z',
      updatedAt: '2026-10-14T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-nov-1',
      feedId: 'preset-christian-holidays',
      title: 'Празднование Казанской иконы Божией Матери',
      description: `### 4 Ноября
Благодарственное церковное празднование заступничества Богородицы и заступления за Русь при освобождении Москвы в 1612 году.`,
      type: 'EVENT' as NoteType,
      startDate: '2026-11-04T00:00:00.000Z',
      endDate: '2026-11-04T23:59:59.000Z',
      icon: 'sparkles',
      tags: [{ id: 'tax-chr-3', name: 'Великие праздники', path: 'church.feasts', icon: 'shield', updatedAt: '2026-11-04T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-nov-1', name: 'КазанскаяИкона', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-04T00:00:00.000Z',
      updatedAt: '2026-11-04T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-nov-2',
      feedId: 'preset-christian-holidays',
      title: 'Собор Архистратига Михаила (Михайлов день)',
      description: `### 21 Ноября
Прославление вождя Небесного воинства Архангела Михаила и всех Небесных сил бесплотных.`,
      type: 'SINGLE' as NoteType,
      startDate: '2026-11-21T08:00:00.000Z',
      endDate: null,
      icon: 'shield',
      tags: [{ id: 'tax-chr-3', name: 'Великие праздники', path: 'church.feasts', icon: 'shield', updatedAt: '2026-11-21T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-nov-2', name: 'МихайловДень', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-21T00:00:00.000Z',
      updatedAt: '2026-11-21T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-nov-3',
      feedId: 'preset-christian-holidays',
      title: 'Начало Рождественского поста (Филиппов пост)',
      description: `### 28 Ноября
Сорокадневный пост духовного очищения и молитвы перед праздником Рождества Христова (по 6 января).`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-11-28T00:00:00.000Z',
      endDate: '2027-01-06T23:59:59.000Z',
      icon: 'bookmark',
      tags: [{ id: 'tax-chr-2', name: 'Пасхальный и годовой цикл', path: 'church.fasts', icon: 'sun', updatedAt: '2026-11-28T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-nov-3', name: 'РождественскийПост', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-28T00:00:00.000Z',
      updatedAt: '2026-11-28T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'chr-hol-dec-1',
      feedId: 'preset-christian-holidays',
      title: 'Введение во храм Пресвятой Богородицы',
      description: `### 4 Декабря
Двунадесятый праздник в память приведения трехлетней Девы Марии в Иерусалимский храм родителями Иоакимом и Анной.`,
      type: 'EVENT' as NoteType,
      startDate: '2026-12-04T00:00:00.000Z',
      endDate: '2026-12-04T23:59:59.000Z',
      icon: 'sparkles',
      tags: [{ id: 'tax-chr-1', name: 'Двунадесятые праздники', path: 'church.great', icon: 'bookmark', updatedAt: '2026-12-04T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-chr-dec-1', name: 'ВведениеВоХрам', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-12-04T00:00:00.000Z',
      updatedAt: '2026-12-04T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
  ],

  'politics-2026': [
    {
      id: 'pol-2026-1',
      feedId: 'preset-politics-2026',
      title: 'Петербургский международный экономический форум (ПМЭФ 2026)',
      description: `### ПМЭФ 2026
Крупнейшее глобальное экономическое событие года: подписание масштабных инфраструктурных контрактов, технологические треки и многополярное сотрудничество.

- **Секции:** Цифровой суверенитет, ИИ-регулирование, логистические коридоры Север-Юг.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-06-03T09:00:00.000Z',
      endDate: '2026-06-06T18:00:00.000Z',
      icon: 'trending-up',
      tags: [{ id: 'tax-pol-1', name: 'Экономические форумы', path: 'politics.forums', icon: 'briefcase', updatedAt: '2026-06-03T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-pol-1', name: 'ПМЭФ2026', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-pol-2', name: 'Экономика', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-06-03T00:00:00.000Z',
      updatedAt: '2026-06-03T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'https://forumspb.com',
    },
    {
      id: 'pol-2026-2',
      feedId: 'preset-politics-2026',
      title: 'Саммит БРИКС+ 2026',
      description: `### XVIII Саммит лидеров государств БРИКС
Ежегодная встреча глав государств-участников объединения БРИКС. Рассмотрение вопросов единой расчетной клиринговой системы и расширения пула валютных резервов.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-07-15T09:00:00.000Z',
      endDate: '2026-07-17T18:00:00.000Z',
      icon: 'globe',
      tags: [{ id: 'tax-pol-2', name: 'Международные саммиты', path: 'politics.summits', icon: 'globe', updatedAt: '2026-07-15T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-pol-3', name: 'БРИКС2026', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-07-15T00:00:00.000Z',
      updatedAt: '2026-07-15T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://brics-russia2026.ru',
    },
    {
      id: 'pol-2026-3',
      feedId: 'preset-politics-2026',
      title: 'Выборы депутатов Государственной Думы РФ IX созыва',
      description: `### Единый день голосования 2026
Всенародные выборы 450 депутатов нижней палаты Федерального Собрания Российской Федерации (смешанная мажоритарно-пропорциональная система).

- Дистанционное электронное голосование (ДЭГ)
- 3-дневное голосование: 18–20 сентября 2026 г.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-09-18T08:00:00.000Z',
      endDate: '2026-09-20T20:00:00.000Z',
      icon: 'vote',
      tags: [{ id: 'tax-pol-3', name: 'Выборы и законодательство', path: 'politics.elections', icon: 'check-square', updatedAt: '2026-09-18T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-pol-4', name: 'Выборы2026', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-pol-5', name: 'Госдума', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-18T00:00:00.000Z',
      updatedAt: '2026-09-18T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'http://cikrf.ru',
    },
    {
      id: 'pol-2026-4',
      feedId: 'preset-politics-2026',
      title: '81-я Сессия Генеральной Ассамблеи ООН',
      description: `### Открытие сессии ГА ООН в Нью-Йорке
Общеполитическая дискуссия мировых лидеров, вопросы глобальной безопасности, устойчивого развития и нераспространения.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-09-22T14:00:00.000Z',
      endDate: '2026-09-29T22:00:00.000Z',
      icon: 'landmark',
      tags: [{ id: 'tax-pol-2', name: 'Международные саммиты', path: 'politics.summits', icon: 'globe', updatedAt: '2026-09-22T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-pol-6', name: 'ООН', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-pol-7', name: 'Геополитика', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-22T00:00:00.000Z',
      updatedAt: '2026-09-22T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'https://un.org',
    },
    {
      id: 'pol-2026-5',
      feedId: 'preset-politics-2026',
      title: 'Саммит «Большой двадцатки» (G20 Summit 2026)',
      description: `### Саммит лидеров G20
Встреча глав государств крупнейших экономик мира. Повестка: продовольственная стабильность, реформа международных финансовых институтов, переход к зеленым технологиям.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-11-14T09:00:00.000Z',
      endDate: '2026-11-16T18:00:00.000Z',
      icon: 'globe',
      tags: [{ id: 'tax-pol-2', name: 'Международные саммиты', path: 'politics.summits', icon: 'globe', updatedAt: '2026-11-14T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-pol-8', name: 'G20', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-14T00:00:00.000Z',
      updatedAt: '2026-11-14T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'pol-2026-6',
      feedId: 'preset-politics-2026',
      title: 'Промежуточные выборы в Конгресс США (US Midterm Elections 2026)',
      description: `### Выборы в Палату представителей и Сенат США
Голосование за все 435 мест в Палате представителей и 33 места в Сенате США, определяющее баланс сил законодательной ветви.`,
      type: 'EVENT' as NoteType,
      startDate: '2026-11-03T12:00:00.000Z',
      endDate: '2026-11-04T06:00:00.000Z',
      icon: 'flag',
      tags: [{ id: 'tax-pol-3', name: 'Выборы и законодательство', path: 'politics.elections', icon: 'check-square', updatedAt: '2026-11-03T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-pol-9', name: 'USPolitics', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-03T00:00:00.000Z',
      updatedAt: '2026-11-03T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'pol-2026-7',
      feedId: 'preset-politics-2026',
      title: 'Климатическая конференция ООН (COP31)',
      description: `### Всемирный климатический саммит
Оценка выполнения Парижского соглашения по сокращению углеродных выбросов и финансированию климатической адаптации развивающихся стран.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-11-09T09:00:00.000Z',
      endDate: '2026-11-20T18:00:00.000Z',
      icon: 'sun',
      tags: [{ id: 'tax-pol-1', name: 'Экономические форумы', path: 'politics.forums', icon: 'briefcase', updatedAt: '2026-11-09T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-pol-10', name: 'COP31', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-09T00:00:00.000Z',
      updatedAt: '2026-11-09T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
  ],

  'wow-calendar': [
    {
      id: 'wow-ev-1',
      feedId: 'preset-wow-calendar',
      title: 'Запуск дополнения World of Warcraft: Midnight',
      description: `### Релиз новой главы саги Worldsoul Saga
Официальный запуск дополнения *World of Warcraft: Midnight*. Возвращение в Кель'Талас, защита Солнечного Колодца от сил Бездны, новые локации и рейдовые подземелья.

- **Максимальный уровень:** 90
- **Новая специализация:** Жрец Бездны / Охотник на демонов Солнечного Пламени`,
      type: 'FILM_RELEASE' as NoteType,
      startDate: '2026-08-25T22:00:00.000Z',
      endDate: null,
      icon: 'sparkles',
      tags: [{ id: 'tax-wow-1', name: 'Релизы дополнений', path: 'wow.expansions', icon: 'zap', updatedAt: '2026-08-25T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-wow-1', name: 'WoWMidnight', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-wow-2', name: 'WorldOfWarcraft', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-08-25T00:00:00.000Z',
      updatedAt: '2026-08-25T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'https://worldofwarcraft.blizzard.com',
    },
    {
      id: 'wow-ev-2',
      feedId: 'preset-wow-calendar',
      title: 'Ярмарка Новолуния (Darkmoon Faire)',
      description: `### Ежемесячная Ярмарка Сайласа Новолуния
Остров Новолуния открыт! Прокачка профессий (+5 к навыкам), карусель с баффом на опыт и репутацию (+10%), сбор карт Новолуния для создания аксессуаров и аркадные игры.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-08-02T00:01:00.000Z',
      endDate: '2026-08-08T23:59:00.000Z',
      icon: 'tent',
      tags: [{ id: 'tax-wow-2', name: 'Игровые праздники', path: 'wow.events', icon: 'gift', updatedAt: '2026-08-02T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-wow-3', name: 'ЯрмаркаНоволуния', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-08-02T00:00:00.000Z',
      updatedAt: '2026-08-02T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'wow-ev-3',
      feedId: 'preset-wow-calendar',
      title: 'Открытие рейдового подземелья «Оплот Бездны» (Мифик)',
      description: `### Гонка за первенство в мире (Race to World First)
Открытие эпохального режима первого рейда Midnight. Лучшие гильдии мира (Echo, Liquid, Method) борются за титул World First в прямом эфире!`,
      type: 'EVENT' as NoteType,
      startDate: '2026-09-08T07:00:00.000Z',
      endDate: '2026-09-18T23:00:00.000Z',
      icon: 'swords',
      tags: [{ id: 'tax-wow-3', name: 'Рейдовые сезоны', path: 'wow.raids', icon: 'shield', updatedAt: '2026-09-08T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-wow-4', name: 'RWF', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-wow-5', name: 'MythicRaid', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-08T00:00:00.000Z',
      updatedAt: '2026-09-08T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'https://raider.io',
    },
    {
      id: 'wow-ev-4',
      feedId: 'preset-wow-calendar',
      title: 'Хмельной фестиваль (Brewfest)',
      description: `### Осенний праздник пивоваров
Гонки на баранах, метание кружек, битва с Кореном Худоваром в Глубинах Черной Горы ради легендарных маунтов: Большого кодо Хмельного фестиваля и Стремительного барана!`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-09-20T08:00:00.000Z',
      endDate: '2026-10-06T20:00:00.000Z',
      icon: 'beer',
      tags: [{ id: 'tax-wow-2', name: 'Игровые праздники', path: 'wow.events', icon: 'gift', updatedAt: '2026-09-20T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-wow-6', name: 'Хмелеварня', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-09-20T00:00:00.000Z',
      updatedAt: '2026-09-20T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'wow-ev-5',
      feedId: 'preset-wow-calendar',
      title: 'Тыквовин (Hallow\'s End)',
      description: `### Праздник Отрекшихся и Хэллоуин в Азероте
Сражение со Всадником без головы на Кладбище Монастыря Алого Ордена. Шанс выбить «Поводья Скакуна Всадника без головы», сладости и праздничные маски.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-10-18T08:00:00.000Z',
      endDate: '2026-11-01T20:00:00.000Z',
      icon: 'skull',
      tags: [{ id: 'tax-wow-2', name: 'Игровые праздники', path: 'wow.events', icon: 'gift', updatedAt: '2026-10-18T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-wow-7', name: 'Тыквовин', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-10-18T00:00:00.000Z',
      updatedAt: '2026-10-18T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'wow-ev-6',
      feedId: 'preset-wow-calendar',
      title: '22-я Годовщина World of Warcraft',
      description: `### Празднование дня рождения легендарной MMORPG
Подарочный пакет с жетонами времени, праздничный бафф на опыт (+22%), мировые боссы классического WoW (Владыка Каззак, Азурегос, Драконы Кошмара) в Танарисе.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-11-06T08:00:00.000Z',
      endDate: '2026-11-27T23:59:00.000Z',
      icon: 'award',
      tags: [{ id: 'tax-wow-2', name: 'Игровые праздники', path: 'wow.events', icon: 'gift', updatedAt: '2026-11-06T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-wow-8', name: 'WoWAnniversary', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-11-06T00:00:00.000Z',
      updatedAt: '2026-11-06T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'wow-ev-7',
      feedId: 'preset-wow-calendar',
      title: 'Праздник Зимнего Покрова (Feast of Winter Veil)',
      description: `### Новый Год и Рождество в Азероте
Дедушка Зима в Стальгорне и Оргриммаре! Подарки под елкой с 25 декабря, бой с Омерзительным Гринчем в Альтеракских горах, метание снежков и полеты на оленях.`,
      type: 'PERIOD' as NoteType,
      startDate: '2026-12-16T08:00:00.000Z',
      endDate: '2027-01-02T20:00:00.000Z',
      icon: 'gift',
      tags: [{ id: 'tax-wow-2', name: 'Игровые праздники', path: 'wow.events', icon: 'gift', updatedAt: '2026-12-16T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-wow-9', name: 'ЗимнийПокров', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-12-16T00:00:00.000Z',
      updatedAt: '2026-12-16T00:00:00.000Z',
      deletedAt: null,
      sourceLink: null,
    },
    {
      id: 'wow-ev-8',
      feedId: 'preset-wow-calendar',
      title: 'Mythic Dungeon International (MDI) Сезон 1 Финалы',
      description: `### Киберспортивный турнир по скоростному прохождению ключей
Трансляция глобальных финалов MDI. Лучшие команды соревнуются в подземельях эпохального уровня сложности +25 на время.`,
      type: 'EVENT' as NoteType,
      startDate: '2026-10-23T16:00:00.000Z',
      endDate: '2026-10-25T23:00:00.000Z',
      icon: 'gamepad-2',
      tags: [{ id: 'tax-wow-4', name: 'Киберспорт', path: 'wow.esports', icon: 'trophy', updatedAt: '2026-10-23T00:00:00.000Z', deletedAt: null }],
      hashtags: [{ id: 'ht-wow-10', name: 'MDI', createdAt: '', updatedAt: '', deletedAt: null }, { id: 'ht-wow-11', name: 'Esports', createdAt: '', updatedAt: '', deletedAt: null }],
      createdAt: '2026-10-23T00:00:00.000Z',
      updatedAt: '2026-10-23T00:00:00.000Z',
      deletedAt: null,
      sourceLink: 'https://youtube.com/Warcraft',
    },
  ],
};
