import { Note, NoteType, PublicFeedPreset } from '@lenta/shared';

export const PUBLIC_FEED_PRESETS: PublicFeedPreset[] = [
  {
    id: 'preset-orthodox-holidays',
    title: 'Православный календарь',
    slug: 'orthodox-holidays',
    icon: '☦️',
    category: 'Православие',
    description: 'Пасха Христова (12 апреля 2026 г.), двунадесятые и великие праздники, многодневные посты и дни памяти святых.',
    color: '#f59e0b',
    count: 24,
  },
  {
    id: 'preset-catholic-holidays',
    title: 'Католический календарь',
    slug: 'catholic-holidays',
    icon: '✝️',
    category: 'Католицизм',
    description: 'Литургический год латинского обряда: Пасха (5 апреля 2026 г.), Пепельная среда, Рождество и главные торжества.',
    color: '#8b5cf6',
    count: 28,
  },
  {
    id: 'preset-islamic-holidays',
    title: 'Исламский календарь',
    slug: 'islamic-holidays',
    icon: '☪️',
    category: 'Ислам (Хиджра)',
    description: 'Священный месяц Рамадан (18 фев – 19 мар), Ночь могущества (Ляйлят аль-Кадр), Ураза-байрам, Курбан-байрам 1447–1448 гг.',
    color: '#10b981',
    count: 10,
  },
  {
    id: 'preset-world-religions',
    title: 'Мировые религии',
    slug: 'world-religions',
    icon: '🕊️',
    category: 'Межконфессиональный',
    description: 'Праздники мировых религий: Ислам (Рамадан, Курбан-байрам), Иудаизм (Песах, Рош ха-Шана, Ханука), Буддизм (Сагаалган, Весак).',
    color: '#06b6d4',
    count: 21,
  },
  {
    id: 'preset-russian-official',
    title: 'Русские государственные праздники',
    slug: 'russian-official',
    icon: '🇷🇺',
    category: 'Праздники РФ',
    description: 'Официальные нерабочие праздничные дни (ТК РФ ст. 112), памятные даты, научные и культурные события 2026 года.',
    color: '#ef4444',
    count: 17,
  },
  {
    id: 'preset-russian-military',
    title: 'Дни воинской славы России',
    slug: 'russian-military',
    icon: '🎖️',
    category: 'Воинская слава РФ',
    description: 'Дни воинской славы России (32-ФЗ), рода войск Вооруженных Сил, исторические сражения и чествование защитников Отечества.',
    color: '#eab308',
    count: 39,
  },
  {
    id: 'preset-world-holidays',
    title: 'Праздники стран мира',
    slug: 'world-holidays',
    icon: '🌍',
    category: 'Праздники стран',
    description: 'Знаменитые праздники стран мира: Китайский Новый год, День взятия Бастилии, День благодарения, Хэллоуин.',
    color: '#3b82f6',
    count: 12,
  },
  {
    id: 'preset-russian-holidays',
    title: 'Все русские праздники (сводный)',
    slug: 'russian-holidays',
    icon: '🇷🇺',
    category: 'Сводный календарь РФ',
    description: 'Полный свод государственных, воинских и профессиональных праздников России в 2026 году.',
    color: '#dc2626',
    count: 56,
  },
  {
    id: 'preset-christian-holidays',
    title: 'Все христианские праздники (сводный)',
    slug: 'christian-holidays',
    icon: '✝️',
    category: 'Христианский мир',
    description: 'Сводный календарь восточной и западной христианских традиций: православные и католические торжества.',
    color: '#d97706',
    count: 52,
  },
  {
    id: 'preset-politics-2026',
    title: 'Политика 2026',
    slug: 'politics-2026',
    icon: '🏛️',
    category: 'Геополитика & Выборы',
    description: 'Ключевые международные саммиты, выборы, парламентские сессии и геополитические соглашения 2026 года.',
    color: '#3b82f6',
    count: 7,
  },
  {
    id: 'preset-wow-calendar',
    title: 'World of Warcraft Календарь',
    slug: 'wow-calendar',
    icon: '⚔️',
    category: 'Игровые события & Рейды',
    description: 'Расписание игровых событий Азерота, открытие рейдов Midnight, Ярмарка Новолуния и сезонные праздники.',
    color: '#a855f7',
    count: 8,
  },
];

// Helper to create valid Tag
const createTag = (id: string, name: string, path: string, icon = 'bookmark') => ({
  id,
  name,
  path,
  icon,
  updatedAt: '2026-01-01T00:00:00.000Z',
  deletedAt: null,
});

// Helper to create valid Hashtag
const createHashtag = (id: string, name: string) => ({
  id,
  name,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  deletedAt: null,
});

// --- 1. RUSSIAN OFFICIAL STATE HOLIDAYS ---
const RUSSIAN_OFFICIAL_NOTES: Note[] = [
  {
    id: 'ru-off-1',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'Новый 2026 Год и Новогодние каникулы',
    description: `### Празднование Нового Года в России
Официальные новогодние праздничные каникулы продлятся с 1 по 8 января 2026 года.
Главные городские ёлки, световые инсталляции и праздничные площадки открыты во всех регионах страны.

- **Даты отдыха:** 1–8 января 2026 г.
- **Статус:** Официальный государственный нерабочий праздничный день (ТК РФ ст. 112).`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-01-08T23:59:59.000Z',
    icon: 'sparkles',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-1', 'НовыйГод'), createHashtag('ht-ru-off-2', 'Праздники2026')],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://government.ru',
  },
  {
    id: 'ru-off-2',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День российского студенчества (Татьянин день)',
    description: `### 25 Января
Памятная дата России в честь основания Московского университета императрицей Елизаветой Петровной в 1755 году. День студенчества и академических традиций.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-01-25T09:00:00.000Z',
    endDate: null,
    icon: 'book-open',
    tags: [createTag('tax-ru-off-2', 'Памятные даты', 'holidays.russia.memorial', 'book')],
    hashtags: [createHashtag('ht-ru-off-3', 'ДеньСтудента'), createHashtag('ht-ru-off-4', 'ТатьянинДень')],
    createdAt: '2026-01-25T00:00:00.000Z',
    updatedAt: '2026-01-25T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-3',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День российской науки',
    description: `### 8 Февраля
В память об учреждении Петром I Академии наук в Санкт-Петербурге 8 февраля 1724 года. Чествование ученых, открытий и научно-технического суверенитета.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-08T09:00:00.000Z',
    endDate: null,
    icon: 'atom',
    tags: [createTag('tax-ru-off-3', 'Профессиональные праздники', 'holidays.russia.science', 'zap')],
    hashtags: [createHashtag('ht-ru-off-5', 'ДеньНауки'), createHashtag('ht-ru-off-6', 'РАН')],
    createdAt: '2026-02-08T00:00:00.000Z',
    updatedAt: '2026-02-08T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-4',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'Международный женский день',
    description: `### 8 Марта
Всенародный государственный нерабочий праздничный день. Чествование женщин, весны, материнства и красоты.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-03-08T08:00:00.000Z',
    endDate: null,
    icon: 'heart',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-7', '8Марта'), createHashtag('ht-ru-off-8', 'ЖенскийДень')],
    createdAt: '2026-03-08T00:00:00.000Z',
    updatedAt: '2026-03-08T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-5',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День космонавтики',
    description: `### 12 Апреля
Памятная дата России в честь первого в мире полета человека в космическое пространство, совершенного Юрием Алексеевичем Гагариным на корабле «Восток-1» в 1961 году. «Поехали!»`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-04-12T09:07:00.000Z',
    endDate: null,
    icon: 'rocket',
    tags: [createTag('tax-ru-off-2', 'Памятные даты', 'holidays.russia.memorial', 'rocket')],
    hashtags: [createHashtag('ht-ru-off-9', 'ДеньКосмонавтики'), createHashtag('ht-ru-off-10', 'Гагарин')],
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: '2026-04-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://roscosmos.ru',
  },
  {
    id: 'ru-off-6',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'Праздник Весны и Труда',
    description: `### 1 Мая — Первомай
Государственный нерабочий праздничный день. Традиционные весенние шествия, открытие городских парков и фонтанов.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-01T10:00:00.000Z',
    endDate: null,
    icon: 'sun',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-11', '1Мая'), createHashtag('ht-ru-off-12', 'МирТрудМай')],
    createdAt: '2026-05-01T00:00:00.000Z',
    updatedAt: '2026-05-01T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-7',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День России',
    description: `### 12 Июня — Главный государственный праздник
День принятия Декларации о государственном суверенитете Российской Федерации. Торжественное вручение Государственных премий РФ в Кремле, концерты на Красной площади и праздничный салют.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-06-12T10:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-13', 'ДеньРоссии'), createHashtag('ht-ru-off-14', 'МояРоссия')],
    createdAt: '2026-06-12T00:00:00.000Z',
    updatedAt: '2026-06-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://kremlin.ru',
  },
  {
    id: 'ru-off-8',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День Государственного флага Российской Федерации',
    description: `### 22 Августа
Праздник в честь государственного триколора. В городах проходят масштабные автопробеги, флешмобы с развертыванием гигантских флагов и молодежные патриотические акции.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-08-22T09:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-ru-off-2', 'Памятные даты', 'holidays.russia.memorial', 'flag')],
    hashtags: [createHashtag('ht-ru-off-15', 'ФлагРоссии'), createHashtag('ht-ru-off-16', 'Триколор')],
    createdAt: '2026-08-22T00:00:00.000Z',
    updatedAt: '2026-08-22T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-9',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День знаний',
    description: `### 1 Сентября
Государственный праздник. Начало нового учебного года для всех школьников, студентов и педагогов России. Первый звонок и открытые уроки.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-09-01T08:00:00.000Z',
    endDate: null,
    icon: 'book-open',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'book')],
    hashtags: [createHashtag('ht-ru-off-17', 'ДеньЗнаний'), createHashtag('ht-ru-off-18', '1Сентября')],
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-10',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День программиста в России',
    description: `### 13 Сентября (256-й день года)
Официальный профессиональный праздник в РФ (Указ Президента РФ № 1034). Отмечается в 256-й день года (2⁸).`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-09-13T09:00:00.000Z',
    endDate: null,
    icon: 'code',
    tags: [createTag('tax-ru-off-3', 'Профессиональные праздники', 'holidays.russia.it', 'code')],
    hashtags: [createHashtag('ht-ru-off-19', 'ДеньПрограммиста'), createHashtag('ht-ru-off-20', 'ITRussia')],
    createdAt: '2026-09-13T00:00:00.000Z',
    updatedAt: '2026-09-13T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-11',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День народного единства',
    description: `### 4 Ноября
Государственный нерабочий праздничный день в память об освобождении Москвы народным ополчением под предводительством Кузьмы Минина и Дмитрия Пожарского в 1612 году.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-04T10:00:00.000Z',
    endDate: null,
    icon: 'users',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'flag')],
    hashtags: [createHashtag('ht-ru-off-21', 'ДеньНародногоЕдинства'), createHashtag('ht-ru-off-22', 'МыЕдины')],
    createdAt: '2026-11-04T00:00:00.000Z',
    updatedAt: '2026-11-04T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-12',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День матери в России',
    description: `### 29 Ноября 2026 (Последнее воскресенье ноября)
Всероссийский праздник любви, глубокого уважения и признательности матерям. Символ праздника — цветок незабудки.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-29T09:00:00.000Z',
    endDate: null,
    icon: 'heart',
    tags: [createTag('tax-ru-off-1', 'Государственные праздники', 'holidays.russia.official', 'heart')],
    hashtags: [createHashtag('ht-ru-off-23', 'ДеньМатери'), createHashtag('ht-ru-off-24', 'СпасибоМама')],
    createdAt: '2026-11-29T00:00:00.000Z',
    updatedAt: '2026-11-29T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-off-13',
    feedId: 'preset-russian-official',
    containerId: 'cont-russian-official',
    title: 'День Конституции Российской Федерации',
    description: `### 12 Декабря
Памятная дата России в честь принятия Конституции РФ на всенародном голосовании 12 декабря 1993 года. Основа государственного строя и правопорядка.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-12-12T09:00:00.000Z',
    endDate: null,
    icon: 'landmark',
    tags: [createTag('tax-ru-off-2', 'Памятные даты', 'holidays.russia.memorial', 'landmark')],
    hashtags: [createHashtag('ht-ru-off-25', 'ДеньКонституции'), createHashtag('ht-ru-off-26', 'КонституцияРФ')],
    createdAt: '2026-12-12T00:00:00.000Z',
    updatedAt: '2026-12-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://kremlin.ru',
  },
];

// --- 2. RUSSIAN MILITARY GLORY & ARMED FORCES DAYS (32-FZ) ---
const RUSSIAN_MILITARY_NOTES: Note[] = [
  {
    id: 'ru-mil-1',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День защитника Отечества',
    description: `### 23 Февраля — День воинской славы России (32-ФЗ)
Всенародный праздник чествования защитников Отечества, ветеранов и действующих военнослужащих армии и флота. Торжественные возложения венков к Могиле Неизвестного Солдата и праздничные салюты.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-23T09:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-1', '23Февраля'), createHashtag('ht-ru-mil-2', 'ДеньЗащитникаОтечества')],
    createdAt: '2026-02-23T00:00:00.000Z',
    updatedAt: '2026-02-23T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://mil.ru',
  },
  {
    id: 'ru-mil-2',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День войск национальной гвардии РФ (Росгвардия)',
    description: `### 27 Марта — День Росгвардии
Профессиональный праздник войск национальной гвардии РФ. Обеспечение общественной безопасности, охрана важных государственных объектов и борьба с терроризмом. «Всегда на страже!»`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-03-27T08:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-3', 'Росгвардия'), createHashtag('ht-ru-mil-4', 'ВВМВД')],
    createdAt: '2026-03-27T00:00:00.000Z',
    updatedAt: '2026-03-27T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://rosguard.gov.ru',
  },
  {
    id: 'ru-mil-3',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День создания Вооруженных Сил Российской Федерации',
    description: `### 7 Мая 1992 года — Основание Вооруженных Сил РФ
Памятный день создания современных ВС РФ на основании Распоряжения Президента Российской Федерации № 219-рп.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-07T09:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-5', 'ВооруженныеСилыРФ'), createHashtag('ht-ru-mil-6', 'АрмияРоссии')],
    createdAt: '2026-05-07T00:00:00.000Z',
    updatedAt: '2026-05-07T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://mil.ru',
  },
  {
    id: 'ru-mil-4',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: '81-я Годовщина Победы в Великой Отечественной войне',
    description: `### 9 Мая — День Победы (32-ФЗ)
Священный всенародный праздник и главный День воинской славы России.
Парад Победы на Красной площади в Москве, шествие «Бессмертного полка», всероссийская минута молчания и грандиозный артиллерийский салют во всех городах-героях.

- **10:00 МСК:** Военный парад на Красной площади
- **19:00 МСК:** Всероссийская минута молчания
- **22:00 МСК:** Праздничный салют Победы`,
    type: 'EVENT' as NoteType,
    startDate: '2026-05-09T07:00:00.000Z',
    endDate: '2026-05-09T22:00:00.000Z',
    icon: 'award',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'star')],
    hashtags: [createHashtag('ht-ru-mil-7', 'ДеньПобеды'), createHashtag('ht-ru-mil-8', '9Мая'), createHashtag('ht-ru-mil-9', 'БессмертныйПолк')],
    createdAt: '2026-05-09T00:00:00.000Z',
    updatedAt: '2026-05-09T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://may9.ru',
  },
  {
    id: 'ru-mil-5',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День пограничника',
    description: `### 28 Мая — День часовых рубежей Родины
Профессиональный праздник сотрудников Пограничной службы ФСБ России. «Граница на замке, а ключ в кармане!» Чествование героев погранвойск.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-28T09:00:00.000Z',
    endDate: null,
    icon: 'shield-alert',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-10', 'ДеньПограничника'), createHashtag('ht-ru-mil-11', 'Погранвойска')],
    createdAt: '2026-05-28T00:00:00.000Z',
    updatedAt: '2026-05-28T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://fsb.ru',
  },
  {
    id: 'ru-mil-6',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День Воздушно-десантных войск (День ВДВ)',
    description: `### 2 Августа — День «Крылатой пехоты»
Праздник гвардейцев-десантников Вооруженных Сил России. «Никто, кроме нас!» Показательные выступления, прыжки с парашютом и встречи ветеранов десанта.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-08-02T09:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'shield')],
    hashtags: [createHashtag('ht-ru-mil-12', 'ДеньВДВ'), createHashtag('ht-ru-mil-13', 'НиктоКромеНас')],
    createdAt: '2026-08-02T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://mil.ru',
  },
  {
    id: 'ru-mil-7',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День Военно-воздушных сил России (День ВВС)',
    description: `### 12 Августа — День ВВС
Памятный день Военно-воздушных сил в составе Воздушно-космических сил РФ. Мастерство пилотажных групп «Русские витязи» и «Стрижи».`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-08-12T09:00:00.000Z',
    endDate: null,
    icon: 'plane',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'plane')],
    hashtags: [createHashtag('ht-ru-mil-14', 'ДеньВВС'), createHashtag('ht-ru-mil-15', 'ВКС')],
    createdAt: '2026-08-12T00:00:00.000Z',
    updatedAt: '2026-08-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-8',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День Бородинского сражения (1812 год)',
    description: `### 8 Сентября — День воинской славы России
Генеральное сражение Отечественной войны 1812 года между русской армией под командованием М.И. Голенищева-Кутузова и французской армией Наполеона Бонапарта.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-09-08T09:00:00.000Z',
    endDate: null,
    icon: 'landmark',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'star')],
    hashtags: [createHashtag('ht-ru-mil-16', 'Бородино'), createHashtag('ht-ru-mil-17', '1812год')],
    createdAt: '2026-09-08T00:00:00.000Z',
    updatedAt: '2026-09-08T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-9',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День победы в Куликовской битве (1380 год)',
    description: `### 21 Сентября — День воинской славы России
Разгром монголо-татарских войск объединенными русскими полками под предводительством великого князя Дмитрия Донского на Куликовом поле.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-09-21T09:00:00.000Z',
    endDate: null,
    icon: 'swords',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'star')],
    hashtags: [createHashtag('ht-ru-mil-18', 'КуликовскаяБитва'), createHashtag('ht-ru-mil-19', 'ДмитрийДонской')],
    createdAt: '2026-09-21T00:00:00.000Z',
    updatedAt: '2026-09-21T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-10',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День подразделений специального назначения (День спецназа)',
    description: `### 24 Октября — Памятный день ВС РФ
День подразделений армейского спецназа в память о директиве Военного министра СССР маршала А.М. Василевского 1950 года о создании рот специального назначения ГРУ.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-10-24T09:00:00.000Z',
    endDate: null,
    icon: 'crosshair',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'crosshair')],
    hashtags: [createHashtag('ht-ru-mil-20', 'ДеньСпецназа'), createHashtag('ht-ru-mil-21', 'СпН')],
    createdAt: '2026-10-24T00:00:00.000Z',
    updatedAt: '2026-10-24T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-11',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День военного разведчика (ГРУ)',
    description: `### 5 Ноября — День военной разведки
Праздник органов военной разведки Главного управления Генерального штаба ВС РФ (ГРУ). «Величие Родины — в твоих славных делах!»`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-05T09:00:00.000Z',
    endDate: null,
    icon: 'eye',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'eye')],
    hashtags: [createHashtag('ht-ru-mil-22', 'ВоеннаяРазведка'), createHashtag('ht-ru-mil-23', 'ГРУ')],
    createdAt: '2026-11-05T00:00:00.000Z',
    updatedAt: '2026-11-05T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-12',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День военного парада на Красной площади (1941 год)',
    description: `### 7 Ноября — День воинской славы России
В память о легендарном историческом военном параде 7 ноября 1941 года, прямо с которого бойцы уходили на фронт защищать Москву.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-07T09:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'star')],
    hashtags: [createHashtag('ht-ru-mil-24', 'Парад1941'), createHashtag('ht-ru-mil-25', 'БитваЗаМоскву')],
    createdAt: '2026-11-07T00:00:00.000Z',
    updatedAt: '2026-11-07T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'ru-mil-13',
    feedId: 'preset-russian-military',
    containerId: 'cont-russian-military',
    title: 'День Ракетных войск стратегического назначения (РВСН)',
    description: `### 17 Декабря — День РВСН
Памятный день стратегических ракетчиков Вооруженных Сил России. Главный ядерный щит и гарант суверенитета Отечества. «После нас — тишина!»`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-12-17T09:00:00.000Z',
    endDate: null,
    icon: 'zap',
    tags: [createTag('tax-ru-mil-1', 'Воинская слава', 'holidays.russia.military', 'zap')],
    hashtags: [createHashtag('ht-ru-mil-26', 'РВСН'), createHashtag('ht-ru-mil-27', 'ЯдерныйЩит')],
    createdAt: '2026-12-17T00:00:00.000Z',
    updatedAt: '2026-12-17T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];

// --- 3. ORTHODOX CHRISTIAN LITURGICAL CALENDAR 2026 ---
const ORTHODOX_NOTES: Note[] = [
  {
    id: 'orth-1',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Рождество Господа Бога и Спаса нашего Иисуса Христа',
    description: `### 7 Января — Двунадесятый господский праздник
Один из величайших праздников Православной Церкви. Торжественные ночные богослужения во всех храмах и соборах, славление Христа и начало святочных дней.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-01-07T00:00:00.000Z',
    endDate: '2026-01-07T23:59:59.000Z',
    icon: 'star',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'star')],
    hashtags: [createHashtag('ht-orth-1', 'РождествоХристово'), createHashtag('ht-orth-2', 'Православие')],
    createdAt: '2026-01-07T00:00:00.000Z',
    updatedAt: '2026-01-07T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://patriarchia.ru',
  },
  {
    id: 'orth-2',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Святое Богоявление (Крещение Господне)',
    description: `### 19 Января — Крещение Спасителя в водах Иордана
Великое водоосвящение (Великая агиасма), традиционные крещенские купания в освященных иорданях и явление Святой Троицы.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-01-19T06:00:00.000Z',
    endDate: null,
    icon: 'droplet',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'droplet')],
    hashtags: [createHashtag('ht-orth-3', 'КрещениеГосподне'), createHashtag('ht-orth-4', 'Богоявление')],
    createdAt: '2026-01-19T00:00:00.000Z',
    updatedAt: '2026-01-19T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-3',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Сретение Господне',
    description: `### 15 Февраля — Встреча Ветхого и Нового Заветов
Принесение Богомладенца Иисуса в Иерусалимский храм на сороковой день по Рождестве и встреча праведным старцем Симеоном и пророчицей Анной. День православной молодежи.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-15T08:00:00.000Z',
    endDate: null,
    icon: 'sparkles',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'sparkles')],
    hashtags: [createHashtag('ht-orth-5', 'СретениеГосподне')],
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: '2026-02-15T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-4',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Вход Господень в Иерусалим (Вербное воскресенье)',
    description: `### 5 Апреля 2026 — Неделя 6-я Великого поста
Торжественный вход Спасителя в священный город Иерусалим накануне крестных страданий. Освящение веточек вербы в воспоминание пальмовых ветвей.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-04-05T08:00:00.000Z',
    endDate: null,
    icon: 'feather',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'feather')],
    hashtags: [createHashtag('ht-orth-6', 'ВербноеВоскресенье')],
    createdAt: '2026-04-05T00:00:00.000Z',
    updatedAt: '2026-04-05T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-5',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Благовещение Пресвятой Богородицы',
    description: `### 7 Апреля
Возвещение архангелом Гавриилом Деве Марии благой вести о непорочном зачатии и рождении Спасителя мира Иисуса Христа. Древний обычай выпускать на волю белых птиц.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-04-07T08:00:00.000Z',
    endDate: null,
    icon: 'sun',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'sun')],
    hashtags: [createHashtag('ht-orth-7', 'Благовещение')],
    createdAt: '2026-04-07T00:00:00.000Z',
    updatedAt: '2026-04-07T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-6',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Светлое Христово Воскресение — ПАСХА',
    description: `### 12 Апреля 2026 г. — Праздников Праздник и Торжество из Торжеств
Главное событие церковного года Православной Церкви. Победа Спасителя над смертью и адом. Доставка Благодатного Огня из Иерусалима, крестные ходы, освящение куличей, пасох и крашеных яиц.

> **«Христос Воскресе! — Воистину Воскресе!»**`,
    type: 'EVENT' as NoteType,
    startDate: '2026-04-12T00:00:00.000Z',
    endDate: '2026-04-12T23:59:59.000Z',
    icon: 'sparkles',
    tags: [createTag('tax-orth-2', 'Пасхальный цикл', 'church.orthodox.easter', 'sparkles')],
    hashtags: [createHashtag('ht-orth-8', 'Пасха2026'), createHashtag('ht-orth-9', 'ХристосВоскресе')],
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: '2026-04-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://patriarchia.ru',
  },
  {
    id: 'orth-7',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Вознесение Господне',
    description: `### 21 Мая 2026 г. (40-й день по Пасхе)
Праздник в память о восшествии Господа Иисуса Христа во плоти на Небо на горе Елеон в присутствии Богородицы и апостолов.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-21T08:00:00.000Z',
    endDate: null,
    icon: 'cloud',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'cloud')],
    hashtags: [createHashtag('ht-orth-10', 'ВознесениеГосподне')],
    createdAt: '2026-05-21T00:00:00.000Z',
    updatedAt: '2026-05-21T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-8',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'День Святой Троицы (Пятидесятница)',
    description: `### 31 Мая 2026 г. (50-й день по Пасхе)
Сошествие Святого Духа на апостолов в Сионской горнице. День рождения Церкви Христовой. Храмы украшаются свежими ветвями берез и весенней зеленью.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-31T08:00:00.000Z',
    endDate: null,
    icon: 'feather',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'feather')],
    hashtags: [createHashtag('ht-orth-11', 'Троица'), createHashtag('ht-orth-12', 'Пятидесятница')],
    createdAt: '2026-05-31T00:00:00.000Z',
    updatedAt: '2026-05-31T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-9',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Успение Пресвятой Богородицы',
    description: `### 28 Августа — Окончание Успенского поста
Блаженная кончина Божией Матери, взятие Ее пречистого тела и души на Небеса Господом Иисусом Христом. Чин погребения Плащаницы Богородицы.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-08-28T08:00:00.000Z',
    endDate: null,
    icon: 'bookmark',
    tags: [createTag('tax-orth-1', 'Двунадесятые праздники', 'church.orthodox.great', 'bookmark')],
    hashtags: [createHashtag('ht-orth-13', 'УспениеБогородицы')],
    createdAt: '2026-08-28T00:00:00.000Z',
    updatedAt: '2026-08-28T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'orth-10',
    feedId: 'preset-orthodox-holidays',
    containerId: 'cont-orthodox-calendar',
    title: 'Покров Пресвятой Богородицы',
    description: `### 14 Октября — Великий праздник
Воспоминание явления Богоматери святому Андрею Юродивому во Влахернском храме Константинополя, распростершей Свой омофор в защиту молящихся.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-10-14T08:00:00.000Z',
    endDate: null,
    icon: 'shield',
    tags: [createTag('tax-orth-3', 'Великие праздники', 'church.orthodox.feasts', 'shield')],
    hashtags: [createHashtag('ht-orth-14', 'ПокровБогородицы')],
    createdAt: '2026-10-14T00:00:00.000Z',
    updatedAt: '2026-10-14T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];

// --- 4. CATHOLIC CHRISTIAN LITURGICAL CALENDAR 2026 ---
const CATHOLIC_NOTES: Note[] = [
  {
    id: 'cath-1',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Богоявление (День трех королей)',
    description: `### 6 Января — Epiphania Domini
Поклонение волхвов (Каспара, Мельхиора и Бальтазара) Младенцу Иисусу. Традиция мелом писать на дверях инициалы «C + M + B 2026».`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-01-06T08:00:00.000Z',
    endDate: null,
    icon: 'crown',
    tags: [createTag('tax-cath-1', 'Католические торжества', 'church.catholic.solemnities', 'crown')],
    hashtags: [createHashtag('ht-cath-1', 'Богоявление'), createHashtag('ht-cath-2', 'ТриКороля')],
    createdAt: '2026-01-06T00:00:00.000Z',
    updatedAt: '2026-01-06T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://vatican.va',
  },
  {
    id: 'cath-2',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Пепельная среда (Начало Великого поста)',
    description: `### 18 Февраля 2026 г. — Dies Cinerum
Начало 40-дневного Великого поста (Quadragesima) в латинском обряде. Обряд посыпания голов освященным пеплом: «Помни, что ты прах, и в прах возвратишься».`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-18T08:00:00.000Z',
    endDate: null,
    icon: 'cross',
    tags: [createTag('tax-cath-2', 'Великий пост', 'church.catholic.lent', 'cross')],
    hashtags: [createHashtag('ht-cath-3', 'ПепельнаяСреда'), createHashtag('ht-cath-4', 'ВеликийПост')],
    createdAt: '2026-02-18T00:00:00.000Z',
    updatedAt: '2026-02-18T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'cath-3',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Пасхальное триденствие: Страстная пятница',
    description: `### 3 Апреля 2026 г. — Good Friday
Воспоминание крестной смерти Спасителя на Голгофе. Поклонение Святому Кресту, тишина алтаря и молитва у Гроба Господня.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-04-03T15:00:00.000Z',
    endDate: '2026-04-03T23:59:59.000Z',
    icon: 'cross',
    tags: [createTag('tax-cath-3', 'Пасхальное триденствие', 'church.catholic.triduum', 'cross')],
    hashtags: [createHashtag('ht-cath-5', 'СтрастнаяПятница'), createHashtag('ht-cath-6', 'Triduum')],
    createdAt: '2026-04-03T00:00:00.000Z',
    updatedAt: '2026-04-03T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'cath-4',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Светлое Христово Воскресение — Католическая Пасха',
    description: `### 5 Апреля 2026 г. — Dominica Resurrectionis
Главное торжество католического литургического года. Ночная Пасхальная вигилия, зажжение Пасхала и апостольское благословение Папы Римского «Urbi et Orbi» («Граду и Миру»).`,
    type: 'EVENT' as NoteType,
    startDate: '2026-04-05T00:00:00.000Z',
    endDate: '2026-04-05T23:59:59.000Z',
    icon: 'sun',
    tags: [createTag('tax-cath-1', 'Католические торжества', 'church.catholic.solemnities', 'sun')],
    hashtags: [createHashtag('ht-cath-7', 'Пасха2026'), createHashtag('ht-cath-8', 'UrbiEtOrbi')],
    createdAt: '2026-04-05T00:00:00.000Z',
    updatedAt: '2026-04-05T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://vatican.va',
  },
  {
    id: 'cath-5',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Торжество Пресвятого Тела и Крови Христа (Corpus Christi)',
    description: `### 4 Июня 2026 г. (Четверг после Троицы)
Праздник евхаристического благодарения. Торжественные процессии со Святыми Дарами по улицам городов и украшение алтарей живыми цветами.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-06-04T09:00:00.000Z',
    endDate: null,
    icon: 'cup',
    tags: [createTag('tax-cath-1', 'Католические торжества', 'church.catholic.solemnities', 'cup')],
    hashtags: [createHashtag('ht-cath-9', 'CorpusChristi'), createHashtag('ht-cath-10', 'Евхаристия')],
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'cath-6',
    feedId: 'preset-catholic-holidays',
    containerId: 'cont-catholic-calendar',
    title: 'Рождество Христово (Christmas)',
    description: `### 25 Декабря — Sollemnitas in Nativitate Domini
Главный зимний праздник латинского обряда. Ночная месса («Пастырка»), вертепы в базиликах и прославление рождения Спасителя.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-12-25T00:00:00.000Z',
    endDate: '2026-12-25T23:59:59.000Z',
    icon: 'star',
    tags: [createTag('tax-cath-1', 'Католические торжества', 'church.catholic.solemnities', 'star')],
    hashtags: [createHashtag('ht-cath-11', 'Christmas'), createHashtag('ht-cath-12', 'Рождество')],
    createdAt: '2026-12-25T00:00:00.000Z',
    updatedAt: '2026-12-25T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://vatican.va',
  },
];

// --- 5. ISLAMIC RELIGIOUS CALENDAR (HIJRI 1447–1448) ---
const ISLAMIC_NOTES: Note[] = [
  {
    id: 'isl-1',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Начало священного месяца Рамадан 1447 г. хиджры',
    description: `### 18 Февраля 2026 г. — Священный месяц поста
Начало девятого месяца мусульманского лунного календаря. Время строгого поста (ураза) от рассвета (фаджр) до заката (магриб), чтения Священного Корана, совершения молитв таравих и благотворительности.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-02-18T00:00:00.000Z',
    endDate: '2026-03-19T23:59:59.000Z',
    icon: 'moon',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'moon')],
    hashtags: [createHashtag('ht-isl-1', 'Рамадан2026'), createHashtag('ht-isl-2', 'RamadanMubarak'), createHashtag('ht-isl-3', 'Ураза')],
    createdAt: '2026-02-18T00:00:00.000Z',
    updatedAt: '2026-02-18T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://dumrf.ru',
  },
  {
    id: 'isl-2',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Ночь могущества и предопределения (Ляйлят аль-Кадр)',
    description: `### Ночь с 15 на 16 Марта 2026 г. (27-я ночь Рамадана)
Благословенная ночь ниспослания первых аятов Священного Корана пророку Мухаммаду через ангела Джибриля. В Коране сказано, что эта ночь «лучше тысячи месяцев». Ночные бдения, дуа и мольбы.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-03-15T18:00:00.000Z',
    endDate: '2026-03-16T06:00:00.000Z',
    icon: 'sparkles',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'sparkles')],
    hashtags: [createHashtag('ht-isl-4', 'ЛяйлятальКадр'), createHashtag('ht-isl-5', 'LaylatAlQadr')],
    createdAt: '2026-03-15T00:00:00.000Z',
    updatedAt: '2026-03-15T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'isl-3',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Ураза-байрам (Ид аль-Фитр) — Праздник разговения',
    description: `### 20 Марта 2026 г. (1 Шавваль 1447 г. хиджры)
Один из двух главных праздников ислама, знаменующий окончание священного месяца Рамадан. Праздничный намаз (гаит-намаз) в мечетях, выплата милостыни закят аль-фитр, посещение родных и праздничная трапеза.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-03-20T05:00:00.000Z',
    endDate: '2026-03-20T23:59:59.000Z',
    icon: 'smile',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'smile')],
    hashtags: [createHashtag('ht-isl-6', 'УразаБайрам'), createHashtag('ht-isl-7', 'ИдальФитр'), createHashtag('ht-isl-8', 'EidMubarak')],
    createdAt: '2026-03-20T00:00:00.000Z',
    updatedAt: '2026-03-20T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://dumrf.ru',
  },
  {
    id: 'isl-4',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'День Арафа (Кульминация Хаджа)',
    description: `### 26 Мая 2026 г. (9 Зуль-хиджа 1447 г. хиджры)
Главный день паломничества в Мекку: стояние паломников в молитве на священной горе Арафат. Для мусульман, не совершающих хадж, пост в день Арафа смывает грехи прошлого и наступающего года.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-26T06:00:00.000Z',
    endDate: null,
    icon: 'mountain',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'mountain')],
    hashtags: [createHashtag('ht-isl-9', 'ДеньАрафа'), createHashtag('ht-isl-10', 'Хадж2026')],
    createdAt: '2026-05-26T00:00:00.000Z',
    updatedAt: '2026-05-26T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'isl-5',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Курбан-байрам (Ид аль-Адха) — Праздник жертвоприношения',
    description: `### 27–30 Мая 2026 г. (10–13 Зуль-хиджа 1447 г. хиджры)
Величайший праздник ислама в память о готовности пророка Ибрахима (Авраама) принести в жертву своего сына. Совершение праздничного намаза, обряд курбана (жертвоприношения), раздача мяса бедным и нуждающимся, дни ташрика.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-05-27T05:00:00.000Z',
    endDate: '2026-05-30T23:59:59.000Z',
    icon: 'heart',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'heart')],
    hashtags: [createHashtag('ht-isl-11', 'КурбанБайрам'), createHashtag('ht-isl-12', 'ИдальАдха'), createHashtag('ht-isl-13', 'EidAlAdha')],
    createdAt: '2026-05-27T00:00:00.000Z',
    updatedAt: '2026-05-27T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://dumrf.ru',
  },
  {
    id: 'isl-6',
    feedId: 'preset-islamic-holidays',
    containerId: 'cont-islamic-calendar',
    title: 'Новый 1448 год по Хиджре (1 Мухаррам)',
    description: `### 16 Июня 2026 г. — Начало нового мусульманского года
Первый день первого месяца Мухаррам. В память о переселении (хиджре) пророка Мухаммада и первых мусульман из Мекки в Медину в 622 году н.э.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-06-16T00:00:00.000Z',
    endDate: null,
    icon: 'calendar',
    tags: [createTag('tax-isl-1', 'Исламский календарь', 'religion.islam', 'calendar')],
    hashtags: [createHashtag('ht-isl-14', 'Хиджра1448'), createHashtag('ht-isl-15', 'МусульманскийНовыйГод')],
    createdAt: '2026-06-16T00:00:00.000Z',
    updatedAt: '2026-06-16T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];

// --- 6. WORLD RELIGIONS (ISLAM, JUDAISM, BUDDHISM) ---
const WORLD_RELIGIONS_NOTES: Note[] = [
  ...ISLAMIC_NOTES.slice(0, 3).map((n) => ({
    ...n,
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
  })),
  {
    id: 'rel-jud-1',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Пурим (Purim)',
    description: `### 3 Марта 2026 г. (14 Адара 5786 г.)
Веселый еврейский праздник в память о чудесном спасении евреев Персидской империи от козней визиря Амана, описанном в Книге Эсфирь (Мегилат Эстер). Чтение свитка, карнавальные костюмы и угощение «уши Амана» (гоменташн).`,
    type: 'EVENT' as NoteType,
    startDate: '2026-03-03T00:00:00.000Z',
    endDate: '2026-03-03T23:59:59.000Z',
    icon: 'gift',
    tags: [createTag('tax-rel-jud', 'Иудаизм', 'religion.judaism', 'star')],
    hashtags: [createHashtag('ht-rel-jud-1', 'Пурим'), createHashtag('ht-rel-jud-2', 'PurimSameach')],
    createdAt: '2026-03-03T00:00:00.000Z',
    updatedAt: '2026-03-03T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'rel-jud-2',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Песах (Еврейская Пасха) — Праздник Свободы',
    description: `### 2–9 Апреля 2026 г. (15–22 Нисана 5786 г.)
Один из главных библейских праздников в память об Исходе сынов Израиля из египетского рабства. Праздничная пасхальная трапеза Седер, чтение Агады и вкушение опресноков (мацы).`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-04-02T18:00:00.000Z',
    endDate: '2026-04-09T21:00:00.000Z',
    icon: 'sun',
    tags: [createTag('tax-rel-jud', 'Иудаизм', 'religion.judaism', 'sun')],
    hashtags: [createHashtag('ht-rel-jud-3', 'Песах'), createHashtag('ht-rel-jud-4', 'Passover')],
    createdAt: '2026-04-02T00:00:00.000Z',
    updatedAt: '2026-04-02T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'rel-jud-3',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Рош ха-Шана — Еврейский Новый 5787 год',
    description: `### 12–13 Сентября 2026 г. (1–2 Тишрея 5787 г.)
Праздник сотворения мира и день суда Всевышнего. Трубление в бараний рог (шофар), обмакивание яблок в мед с пожеланием «Сладкого и доброго Нового года» (Шана това у-метука).`,
    type: 'EVENT' as NoteType,
    startDate: '2026-09-12T00:00:00.000Z',
    endDate: '2026-09-13T23:59:59.000Z',
    icon: 'bell',
    tags: [createTag('tax-rel-jud', 'Иудаизм', 'religion.judaism', 'bell')],
    hashtags: [createHashtag('ht-rel-jud-5', 'РошХаШана'), createHashtag('ht-rel-jud-6', 'ШанаТова')],
    createdAt: '2026-09-12T00:00:00.000Z',
    updatedAt: '2026-09-12T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'rel-bud-1',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Сагаалган (Белый Месяц) — Буддийский Новый год',
    description: `### 18 Февраля 2026 г. — Год Огненной Лошади
Главный праздник монголо- и тюркоязычных буддийских народов России (Бурятия, Калмыкия, Тува). Очистительный молебен Дугжууба, белая пища, благопожелания старшим и духовное обновление.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-02-18T06:00:00.000Z',
    endDate: null,
    icon: 'sparkles',
    tags: [createTag('tax-rel-bud', 'Буддизм', 'religion.buddhism', 'sparkles')],
    hashtags: [createHashtag('ht-rel-bud-1', 'Сагаалган'), createHashtag('ht-rel-bud-2', 'БелыйМесяц'), createHashtag('ht-rel-bud-3', 'БуддизмРоссии')],
    createdAt: '2026-02-18T00:00:00.000Z',
    updatedAt: '2026-02-18T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'rel-bud-2',
    feedId: 'preset-world-religions',
    containerId: 'cont-world-religions',
    title: 'Весак (Дончод-хурал) — День рождения Будды',
    description: `### 31 Мая 2026 г. (Полнолуние месяца Вайшакха)
Священный тройной праздник буддийского мира: день Рождения, Просветления (Бодхи) и ухода в Паринирвану Будды Шакьямуни. Зажжение светильников, обход храмов (гороо) и созерцание.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-05-31T06:00:00.000Z',
    endDate: null,
    icon: 'sun',
    tags: [createTag('tax-rel-bud', 'Буддизм', 'religion.buddhism', 'sun')],
    hashtags: [createHashtag('ht-rel-bud-4', 'Весак'), createHashtag('ht-rel-bud-5', 'ДеньБудды')],
    createdAt: '2026-05-31T00:00:00.000Z',
    updatedAt: '2026-05-31T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];

// --- 7. WORLD COUNTRIES HOLIDAYS ---
const WORLD_HOLIDAYS_NOTES: Note[] = [
  {
    id: 'w-hol-1',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'Китайский Новый год (Чуньцзе — Праздник Весны)',
    description: `### 17 Февраля 2026 г. — Наступление года Огненной Лошади
Традиционный праздник встречи Нового года по лунному календарю в Китае и странах Восточной Азии. Красные фонари, танец дракона и семейные застолья.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-02-17T00:00:00.000Z',
    endDate: '2026-02-17T23:59:59.000Z',
    icon: 'sparkles',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'globe')],
    hashtags: [createHashtag('ht-w-hol-1', 'КитайскийНовыйГод'), createHashtag('ht-w-hol-2', 'ChunJie')],
    createdAt: '2026-02-17T00:00:00.000Z',
    updatedAt: '2026-02-17T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-2',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'День святого Патрика (St. Patrick\'s Day)',
    description: `### 17 Марта — Национальный праздник Ирландии
Всемирный праздник ирландской культуры. Зеленый цвет, лист трилистника (shamrock), шествия волынщиков и парады от Дублина до Нью-Йорка.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-03-17T10:00:00.000Z',
    endDate: null,
    icon: 'clover',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'globe')],
    hashtags: [createHashtag('ht-w-hol-3', 'ДеньСвятогоПатрика'), createHashtag('ht-w-hol-4', 'StPatricksDay')],
    createdAt: '2026-03-17T00:00:00.000Z',
    updatedAt: '2026-03-17T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-3',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'День независимости США (4th of July)',
    description: `### 4 Июля 1776 года
Государственный праздник в честь принятия Декларации независимости Соединенных Штатов Америки. Традиционные фейерверки, барбекю и патриотические парады.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-07-04T12:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'flag')],
    hashtags: [createHashtag('ht-w-hol-5', '4thOfJuly'), createHashtag('ht-w-hol-6', 'IndependenceDay')],
    createdAt: '2026-07-04T00:00:00.000Z',
    updatedAt: '2026-07-04T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-4',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'Национальный праздник Франции (День взятия Бастилии)',
    description: `### 14 Июля 1789 года
Годовщина взятия крепости Бастилия. Грандиозный военный парад на Елисейских полях в Париже в присутствии Президента Франции и огни Эйфелевой башни.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-07-14T10:00:00.000Z',
    endDate: null,
    icon: 'flag',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'flag')],
    hashtags: [createHashtag('ht-w-hol-7', 'ДеньБастилии'), createHashtag('ht-w-hol-8', 'BastilleDay')],
    createdAt: '2026-07-14T00:00:00.000Z',
    updatedAt: '2026-07-14T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-5',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'Хэллоуин (Канун Дня всех святых)',
    description: `### 31 Октября
Праздник костюмов, тыквенных фонариков Джека (Jack-o'-lantern) и традиции «Trick or Treat» («Сладость или гадость»), популярный во всем мире.`,
    type: 'EVENT' as NoteType,
    startDate: '2026-10-31T18:00:00.000Z',
    endDate: '2026-10-31T23:59:59.000Z',
    icon: 'skull',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'skull')],
    hashtags: [createHashtag('ht-w-hol-9', 'Halloween'), createHashtag('ht-w-hol-10', 'Хэллоуин')],
    createdAt: '2026-10-31T00:00:00.000Z',
    updatedAt: '2026-10-31T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'w-hol-6',
    feedId: 'preset-world-holidays',
    containerId: 'cont-world-holidays',
    title: 'День благодарения (Thanksgiving Day)',
    description: `### 26 Ноября 2026 г. (Четвертый четверг ноября)
Традиционный американский и канадский праздник выражения благодарности за урожай и блага года. Запеченная индейка, тыквенный пирог и семейный круг.`,
    type: 'SINGLE' as NoteType,
    startDate: '2026-11-26T14:00:00.000Z',
    endDate: null,
    icon: 'heart',
    tags: [createTag('tax-w-hol', 'Праздники стран мира', 'holidays.world', 'heart')],
    hashtags: [createHashtag('ht-w-hol-11', 'Thanksgiving'), createHashtag('ht-w-hol-12', 'ДеньБлагодарения')],
    createdAt: '2026-11-26T00:00:00.000Z',
    updatedAt: '2026-11-26T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];

// --- 8. POLITICS 2026 ---
const POLITICS_NOTES: Note[] = [
  {
    id: 'pol-2026-1',
    feedId: 'preset-politics-2026',
    title: 'Петербургский международный экономический форум (ПМЭФ 2026)',
    description: `### ПМЭФ 2026
Крупнейшее глобальное экономическое событие года: подписание инфраструктурных контрактов, технологические треки и многополярное сотрудничество.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-06-03T09:00:00.000Z',
    endDate: '2026-06-06T18:00:00.000Z',
    icon: 'trending-up',
    tags: [createTag('tax-pol-1', 'Экономические форумы', 'politics.forums', 'briefcase')],
    hashtags: [createHashtag('ht-pol-1', 'ПМЭФ2026'), createHashtag('ht-pol-2', 'Экономика')],
    createdAt: '2026-06-03T00:00:00.000Z',
    updatedAt: '2026-06-03T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://forumspb.com',
  },
  {
    id: 'pol-2026-2',
    feedId: 'preset-politics-2026',
    title: 'Саммит БРИКС+ 2026',
    description: `### XVIII Саммит лидеров государств БРИКС
Ежегодная встреча глав государств-участников объединения БРИКС. Рассмотрение вопросов клиринговой системы и расширения пула валютных резервов.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-07-15T09:00:00.000Z',
    endDate: '2026-07-17T18:00:00.000Z',
    icon: 'globe',
    tags: [createTag('tax-pol-2', 'Международные саммиты', 'politics.summits', 'globe')],
    hashtags: [createHashtag('ht-pol-3', 'БРИКС2026')],
    createdAt: '2026-07-15T00:00:00.000Z',
    updatedAt: '2026-07-15T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'pol-2026-3',
    feedId: 'preset-politics-2026',
    title: 'Выборы депутатов Государственной Думы РФ IX созыва',
    description: `### Единый день голосования 2026
Всенародные выборы 450 депутатов нижней палаты Федерального Собрания Российской Федерации.
3-дневное голосование: 18–20 сентября 2026 г.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-09-18T08:00:00.000Z',
    endDate: '2026-09-20T20:00:00.000Z',
    icon: 'vote',
    tags: [createTag('tax-pol-3', 'Выборы', 'politics.elections', 'check-square')],
    hashtags: [createHashtag('ht-pol-4', 'Выборы2026'), createHashtag('ht-pol-5', 'Госдума')],
    createdAt: '2026-09-18T00:00:00.000Z',
    updatedAt: '2026-09-18T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'http://cikrf.ru',
  },
  {
    id: 'pol-2026-4',
    feedId: 'preset-politics-2026',
    title: '81-я Сессия Генеральной Ассамблеи ООН',
    description: `### Открытие сессии ГА ООН в Нью-Йорке
Общеполитическая дискуссия мировых лидеров, вопросы глобальной безопасности и устойчивого развития.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-09-22T14:00:00.000Z',
    endDate: '2026-09-29T22:00:00.000Z',
    icon: 'landmark',
    tags: [createTag('tax-pol-2', 'Международные саммиты', 'politics.summits', 'globe')],
    hashtags: [createHashtag('ht-pol-6', 'ООН'), createHashtag('ht-pol-7', 'Геополитика')],
    createdAt: '2026-09-22T00:00:00.000Z',
    updatedAt: '2026-09-22T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://un.org',
  },
];

// --- 9. WOW CALENDAR ---
const WOW_NOTES: Note[] = [
  {
    id: 'wow-ev-1',
    feedId: 'preset-wow-calendar',
    title: 'Запуск дополнения World of Warcraft: Midnight',
    description: `### Релиз новой главы саги Worldsoul Saga
Официальный запуск дополнения World of Warcraft: Midnight. Возвращение в Кель'Талас, защита Солнечного Колодца от Бездны, новые рейдовые подземелья.`,
    type: 'FILM_RELEASE' as NoteType,
    startDate: '2026-08-25T22:00:00.000Z',
    endDate: null,
    icon: 'sparkles',
    tags: [createTag('tax-wow-1', 'Релизы', 'wow.expansions', 'zap')],
    hashtags: [createHashtag('ht-wow-1', 'WoWMidnight'), createHashtag('ht-wow-2', 'WorldOfWarcraft')],
    createdAt: '2026-08-25T00:00:00.000Z',
    updatedAt: '2026-08-25T00:00:00.000Z',
    deletedAt: null,
    sourceLink: 'https://worldofwarcraft.blizzard.com',
  },
  {
    id: 'wow-ev-2',
    feedId: 'preset-wow-calendar',
    title: 'Ярмарка Новолуния (Darkmoon Faire)',
    description: `### Ежемесячная Ярмарка Сайласа Новолуния
Прокачка профессий (+5 к навыкам), карусель с баффом на опыт и репутацию (+10%), сбор карт Новолуния для создания аксессуаров и аркадные игры.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-08-02T00:01:00.000Z',
    endDate: '2026-08-08T23:59:00.000Z',
    icon: 'tent',
    tags: [createTag('tax-wow-2', 'Игровые события', 'wow.events', 'gift')],
    hashtags: [createHashtag('ht-wow-3', 'ЯрмаркаНоволуния')],
    createdAt: '2026-08-02T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'wow-ev-3',
    feedId: 'preset-wow-calendar',
    title: 'Хмельной фестиваль (Brewfest)',
    description: `### Осенний праздник пивоваров
Гонки на баранах, метание кружек, битва с Кореном Худоваром в Глубинах Черной Горы ради легендарных маунтов: Большого кодо Хмельного фестиваля и Стремительного барана!`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-09-20T08:00:00.000Z',
    endDate: '2026-10-06T20:00:00.000Z',
    icon: 'beer',
    tags: [createTag('tax-wow-2', 'Игровые события', 'wow.events', 'gift')],
    hashtags: [createHashtag('ht-wow-6', 'Хмелеварня')],
    createdAt: '2026-09-20T00:00:00.000Z',
    updatedAt: '2026-09-20T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
  {
    id: 'wow-ev-4',
    feedId: 'preset-wow-calendar',
    title: 'Праздник Зимнего Покрова (Feast of Winter Veil)',
    description: `### Новый Год и Рождество в Азероте
Дедушка Зима в Стальгорне и Оргриммаре! Подарки под елкой с 25 декабря, бой с Омерзительным Гринчем в Альтеракских горах, метание снежков и полеты на оленях.`,
    type: 'PERIOD' as NoteType,
    startDate: '2026-12-16T08:00:00.000Z',
    endDate: '2027-01-02T20:00:00.000Z',
    icon: 'gift',
    tags: [createTag('tax-wow-2', 'Игровые события', 'wow.events', 'gift')],
    hashtags: [createHashtag('ht-wow-9', 'ЗимнийПокров')],
    createdAt: '2026-12-16T00:00:00.000Z',
    updatedAt: '2026-12-16T00:00:00.000Z',
    deletedAt: null,
    sourceLink: null,
  },
];

// Unified Record mapping every preset slug to its rich sample note set
export const PRESET_SAMPLE_NOTES: Record<string, Note[]> = {
  'russian-official': RUSSIAN_OFFICIAL_NOTES,
  'russian-military': RUSSIAN_MILITARY_NOTES,
  'orthodox-holidays': ORTHODOX_NOTES,
  'catholic-holidays': CATHOLIC_NOTES,
  'islamic-holidays': ISLAMIC_NOTES,
  'world-religions': WORLD_RELIGIONS_NOTES,
  'world-holidays': WORLD_HOLIDAYS_NOTES,
  // Umbrella feeds combining sets for backward compatibility
  'russian-holidays': [...RUSSIAN_OFFICIAL_NOTES, ...RUSSIAN_MILITARY_NOTES],
  'christian-holidays': [...ORTHODOX_NOTES, ...CATHOLIC_NOTES],
  'politics-2026': POLITICS_NOTES,
  'wow-calendar': WOW_NOTES,
};
